BEGIN TRANSACTION;
INSERT OR IGNORE INTO categorias (nombre, url_icono) VALUES
('ALIMENTOS','cat_alimentos.png'),
('ANIMALES','cat_animals.png'),
('AUTOMÓVILES','cat_autos.png'),
('APELLIDOS','cat_apellido.png'),
('COLORES','cat_color.png'),
('DEPORTES','cat_deportes.png'),
('ELEMENTOS','cat_elementos.png'),
('FLORES','cat_flowers.png'),
('HERRAMIENTAS','cat_herramientas.png'),
('HOGAR','cat_hogar.png'),
('INSTRUMENTOS','cat_instrumentos.png'),
('MARCAS','cat_marcas.png'),
('PAISES','cat_paises.png'),
('PELICULAS','cat_peliculas.png'),
('ROPA','cat_prendas.png'),
('PROFESIONES','cat_profesiones.png'),
('HEROES','cat_super.png');

INSERT OR IGNORE INTO palabras (id_categoria, palabra, pista) VALUES (1,'MANZANA','Fruta común de color rojo o verde'),
 (1,'PLATANO','Fruta amarilla y alargada'),
 (1,'SANDIA','Fruta grande con pulpa roja y muchas semillas'),
 (1,'MELON','Fruta dulce de pulpa anaranjada o verde'),
 (1,'PERA','Fruta jugosa con forma característica'),
 (1,'DURAZNO','Fruta con piel suave y hueso al centro'),
 (1,'FRESA','Fruta pequeña roja con semillas por fuera'),
 (1,'CEREZA','Fruta pequeña y roja con hueso'),
 (1,'UVA','Fruta que crece en racimos'),
 (1,'MANGO','Fruta tropical muy jugosa y dulce'),
 (1,'PIÑA','Fruta tropical con cáscara áspera'),
 (1,'COCO','Fruta dura con agua en su interior'),
 (1,'PAPAYA','Fruta tropical de pulpa anaranjada'),
 (1,'KIWI','Fruta pequeña con interior verde'),
 (1,'NARANJA','Fruta cítrica rica en vitamina C'),
 (1,'LIMON','Fruta ácida muy usada en bebidas'),
 (1,'TORONJA','Fruta cítrica de sabor amargo'),
 (1,'GUAYABA','Fruta tropical con muchas semillas'),
 (1,'ZANAHORIA','Verdura anaranjada y crujiente'),
 (1,'PAPA','Tubérculo muy consumido en todo el mundo'),
 (1,'CEBOLLA','Verdura que hace llorar al cortarla'),
 (1,'AJO','Pequeño pero con sabor intenso'),
 (1,'LECHUGA','Base de muchas ensaladas'),
 (1,'ESPINACA','Hoja verde rica en hierro'),
 (1,'BROCOLI','Verdura verde con forma de árbol'),
 (1,'COLIFLOR','Parecida al brócoli pero blanca'),
 (1,'PEPINO','Verdura fresca y crujiente'),
 (1,'JITOMATE','Fruto rojo muy usado en cocina'),
 (1,'AGUACATE','Fruto cremoso de color verde'),
 (1,'CHILE','Ingrediente picante muy usado'),
 (1,'ARROZ','Grano básico en muchas culturas'),
 (1,'FRIJOL','Leguminosa muy común en platillos'),
 (1,'LENTEJA','Pequeña legumbre nutritiva'),
 (1,'GARBANZO','Legumbre usada en hummus'),
 (1,'MAIZ','Grano base de muchas culturas'),
 (1,'PAN','Alimento básico hecho con harina'),
 (1,'TORTILLA','Base de muchos platillos mexicanos'),
 (1,'QUESO','Derivado de la leche'),
 (1,'LECHE','Bebida blanca nutritiva'),
 (1,'YOGUR','Derivado fermentado de la leche'),
 (1,'MANTEQUILLA','Grasa derivada de la leche'),
 (1,'HUEVO','Ingrediente básico en muchas recetas'),
 (1,'CARNE','Fuente de proteína animal'),
 (1,'POLLO','Ave muy consumida en la cocina'),
 (1,'PESCADO','Animal acuático comestible'),
 (1,'CAMARON','Marisco pequeño y sabroso'),
 (1,'SALMON','Pescado rosado muy apreciado'),
 (1,'ATUN','Muy usado en ensaladas'),
 (1,'HAMBURGUESA','Comida rápida con carne y pan'),
 (1,'PIZZA','Platillo italiano con queso y salsa'),
 (1,'TACO','Platillo típico mexicano'),
 (1,'BURRITO','Tortilla rellena y enrollada'),
 (1,'SUSHI','Platillo japonés con arroz y pescado'),
 (1,'RAMEN','Sopa japonesa con fideos'),
 (1,'PASTA','Alimento italiano a base de trigo'),
 (1,'LASAÑA','Platillo en capas con pasta y carne'),
 (1,'ESPAGUETI','Tipo de pasta larga'),
 (1,'ENSALADA','Mezcla de verduras frescas'),
 (1,'SOPA','Platillo líquido caliente'),
 (1,'CALDO','Preparación líquida con ingredientes'),
 (1,'HELADO','Postre frío y dulce'),
 (1,'PASTEL','Postre dulce para celebraciones'),
 (1,'GALLETA','Dulce horneado pequeño'),
 (1,'CHOCOLATE','Dulce derivado del cacao'),
 (1,'CARAMELO','Dulce hecho con azúcar derretida'),
 (1,'MIEL','Dulce natural producido por abejas'),
 (1,'AZUCAR','Endulzante común'),
 (1,'SAL','Condimento básico en la cocina'),
 (2,'PERRO','Fiel compañero del hombre'),
 (2,'GATO','Cazador silencioso de casa'),
 (2,'ELEFANTE','El más grande en tierra'),
 (2,'LEON','Existen peliculas con su seudonimo'),
 (2,'TIGRE','Felino rayado y solitario'),
 (2,'JIRAFA','Alcanza alimentos muy altos'),
 (2,'CEBRA','Parece caballo pero en blanco y negro'),
 (2,'CABALLO','Rápido y útil en el campo'),
 (2,'VACA','Da leche y vive en granjas'),
 (2,'CERDO','Asociado a granjas y barro'),
 (2,'OVEJA','Su lana se usa en ropa'),
 (2,'CABRA','Trepa y come casi todo'),
 (2,'GALLO','Canta al amanecer'),
 (2,'GALLINA','Pone huevos'),
 (2,'PATO','Camina y nada torpemente'),
 (2,'AGUILA','Ave de gran visión'),
 (2,'HALCON','Cazador veloz en el aire'),
 (2,'BUHO','Activo de noche'),
 (2,'MURCIELAGO','Vuela y usa eco'),
 (2,'DELFIN','Muy inteligente en el mar'),
 (2,'BALLENA','Gigante del océano'),
 (2,'TIBURON','Depredador marino temido'),
 (2,'PULPO','Ocho brazos y muy astuto'),
 (2,'CALAMAR','Similar al pulpo pero más alargado'),
 (2,'MEDUSA','Puede picar en el agua'),
 (2,'CANGREJO','Camina de lado'),
 (2,'LANGOSTA','Marisco de caparazón duro'),
 (2,'RANA','Salta y vive en agua y tierra'),
 (2,'SAPO','Parecido a la rana pero más seco'),
 (2,'COCODRILO','Reptil grande y peligroso'),
 (2,'LAGARTO','Reptil pequeño y rápido'),
 (2,'SERPIENTE','Se desliza sin patas'),
 (2,'TORTUGA','Lenta y con caparazón'),
 (2,'IGUANA','Reptil común en climas cálidos'),
 (2,'MONO','Primate juguetón'),
 (2,'GORILA','Primate fuerte y grande'),
 (2,'CHIMPANCE','Muy inteligente y social'),
 (2,'OSO','Grande y peludo'),
 (2,'LOBO','Caza en manada'),
 (2,'ZORRO','Astuto y sigiloso'),
 (2,'HORMIGA','Trabaja en colonia'),
 (2,'ABEJA','Produce miel'),
 (2,'MOSCA','Insecto molesto'),
 (2,'MOSQUITO','Pica y chupa sangre'),
 (2,'ARAÑA','Teje telarañas'),
 (2,'ESCORPION','Tiene aguijón venenoso'),
 (2,'CARACOL','Lento y con concha'),
 (2,'ERIZO','Cubierto de espinas'),
 (2,'CONEJO','Orejas largas y salta'),
 (2,'HAMSTER','Pequeño y común como mascota'),
 (3,'GARCIA','Uno de los más comunes en México'),
 (3,'HERNANDEZ','Muy frecuente en registros civiles'),
 (3,'LOPEZ','Corto y muy común en Latinoamérica'),
 (3,'MARTINEZ','Termina en EZ y es muy popular'),
 (3,'GONZALEZ','De los más repetidos en el país'),
 (3,'RODRIGUEZ','Apellido largo muy conocido'),
 (3,'PEREZ','Muy común y fácil de reconocer'),
 (3,'SANCHEZ','Frecuente en documentos oficiales'),
 (3,'RAMIREZ','Apellido clásico en México'),
 (3,'CRUZ','Corto y muy usado'),
 (3,'FLORES','Relacionado con naturaleza'),
 (3,'GOMEZ','Popular en varios países latinos'),
 (3,'DIAZ','Apellido breve y común'),
 (3,'REYES','Asociado a festividades religiosas'),
 (3,'MORALES','Frecuente en muchas familias'),
 (3,'ORTIZ','Apellido corto y conocido'),
 (3,'GUTIERREZ','Largo y muy común'),
 (3,'CHAVEZ','Muy presente en Latinoamérica'),
 (3,'RUIZ','Apellido corto y tradicional'),
 (3,'ALVAREZ','Muy común en México'),
 (3,'CASTILLO','Relacionado con construcciones antiguas'),
 (3,'TORRES','Asociado a estructuras altas'),
 (3,'RIVERA','Relacionado con cuerpos de agua'),
 (3,'VARGAS','Frecuente en varios países'),
 (3,'ROMERO','Relacionado con una planta'),
 (3,'MENDOZA','Apellido bastante reconocido'),
 (3,'AGUILAR','Relacionado con un ave'),
 (3,'MEDINA','Apellido de origen antiguo'),
 (3,'CASTRO','Frecuente en América Latina'),
 (3,'GUZMAN','Muy común en México'),
 (3,'VELAZQUEZ','Apellido largo y distintivo'),
 (3,'RAMOS','Relacionado con partes de un árbol'),
 (3,'CARRILLO','Frecuente en el norte del país'),
 (3,'DOMINGUEZ','Relacionado con un nombre propio'),
 (3,'SALAZAR','Apellido tradicional latino'),
 (3,'SOTO','Apellido corto y conocido'),
 (3,'PENA','Puede referirse a un sentimiento'),
 (3,'ROJAS','Relacionado con un color'),
 (3,'DELGADO','Apellido común con significado físico'),
 (3,'CORTES','Relacionado con la historia'),
 (3,'NAVARRO','Apellido de origen geográfico'),
 (3,'VALDEZ','Muy común en México'),
 (3,'MALDONADO','Apellido largo y frecuente'),
 (3,'IBARRA','Apellido muy común en el norte'),
 (3,'ESPINOZA','Relacionado con plantas espinosas'),
 (3,'FUENTES','Relacionado con agua'),
 (3,'CAMACHO','Apellido distintivo y conocido'),
 (3,'CERVANTES','Relacionado con literatura famosa'),
 (3,'MIRANDA','Apellido común en varios países'),
 (3,'ZAMORA','Apellido de origen geográfico'),
 (4,'ROJO','Color asociado al fuego y la sangre'),
 (4,'AZUL','Color del cielo despejado'),
 (4,'VERDE','Color de la naturaleza'),
 (4,'AMARILLO','Color brillante como el sol'),
 (4,'NEGRO','Ausencia de luz'),
 (4,'BLANCO','Color de la nieve'),
 (4,'GRIS','Intermedio entre blanco y negro'),
 (4,'CAFE','Color del grano tostado'),
 (4,'NARANJA','Color de una fruta cítrica'),
 (4,'ROSA','Color suave asociado a una flor'),
 (4,'MORADO','Mezcla de rojo y azul'),
 (4,'VIOLETA','Similar al morado pero más intenso'),
 (4,'TURQUESA','Entre azul y verde claro'),
 (4,'CELESTE','Azul muy claro'),
 (4,'DORADO','Color del oro'),
 (4,'PLATEADO','Color del metal brillante'),
 (4,'BEIGE','Tono claro cercano al café'),
 (4,'OLIVA','Verde oscuro con tono amarillento'),
 (4,'SALMON','Rosa con tono anaranjado'),
 (4,'LILA','Tono claro de morado'),
 (4,'MAGENTA','Color intenso entre rojo y violeta'),
 (4,'CIAN','Azul verdoso brillante'),
 (4,'INDIGO','Azul oscuro profundo'),
 (4,'MARINO','Azul muy oscuro'),
 (4,'CORAL','Rosa con matiz anaranjado'),
 (4,'CHOCOLATE','Cafe oscuro como el dulce'),
 (4,'ARENA','Color claro similar a la playa'),
 (4,'MENTA','Verde claro y fresco'),
 (4,'LAVANDA','Tono suave entre violeta y gris'),
 (4,'CARMIN','Rojo intenso y profundo'),
 (5,'FUTBOL','Se juega con un balón y dos porterías'),
 (5,'BASQUETBOL','Encestar el balón es el objetivo'),
 (5,'BEISBOL','Se batea y se corre entre bases'),
 (5,'TENIS','Se juega con raqueta y red'),
 (5,'BOXEO','Combate con guantes en un ring'),
 (5,'ATLETISMO','Incluye carreras y saltos'),
 (5,'NATACION','Se practica dentro del agua'),
 (5,'CICLISMO','Se compite usando bicicleta'),
 (5,'GOLF','Se golpea una bola hacia un hoyo'),
 (5,'RUGBY','Parecido al futbol pero con las manos'),
 (5,'HOCKEY','Se juega con un palo y un disco'),
 (5,'VOLEIBOL','Se pasa el balón sobre una red'),
 (5,'BALONMANO','Se juega lanzando un balón con la mano'),
 (5,'ESGRIMA','Combate con espada'),
 (5,'JUDO','Arte marcial de origen japones'),
 (5,'KARATE','Disciplina de combate sin armas'),
 (5,'TAEKWONDO','Arte marcial con patadas'),
 (5,'SURFING','Se practica sobre olas del mar'),
 (5,'SKATE','Se usa una tabla con ruedas'),
 (5,'SNOWBOARD','Similar al esquí pero con tabla'),
 (5,'ESQUI','Se desliza sobre nieve'),
 (5,'PATINAJE','Se usan patines para deslizarse'),
 (5,'AUTOMOVILISMO','Carreras de autos'),
 (5,'MOTOCICLISMO','Carreras en motocicleta'),
 (5,'ZUMO','Combate cuerpo a cuerpo'),
 (5,'LUCHALIBRE','Versión espectacular de combate'),
 (5,'HALTEROFILIA','Levantamiento de pesas'),
 (5,'GIMNASIA','Movimientos acrobáticos'),
 (5,'TRIATLON','Combina tres disciplinas'),
 (5,'DUATLON','Combina carrera y ciclismo'),
 (5,'PENTATLON','Incluye varias pruebas diferentes'),
 (5,'TIRO','Se dispara a un objetivo'),
 (5,'ARQUERIA','Uso de arco y flechas'),
 (5,'ESCALADA','Subir superficies verticales'),
 (5,'REMO','Se avanza con remos en agua'),
 (5,'CANOTAJE','Se navega en canoa'),
 (5,'KAYAK','Se usa una embarcacion ligera'),
 (5,'POLO','Se juega a caballo con un mazo'),
 (5,'CRICKET','Deporte con bate y pelota'),
 (5,'SOFTBOL','Similar al beisbol pero diferente tamaño'),
 (6,'HIDROGENO','El elemento mas ligero de todos'),
 (6,'HELIO','Gas usado en globos'),
 (6,'LITIO','Usado en baterias recargables'),
 (6,'BERILIO','Metal ligero poco comun'),
 (6,'BORO','Elemento presente en detergentes'),
 (6,'CARBONO','Base de la vida organica'),
 (6,'NITROGENO','Principal componente del aire'),
 (6,'OXIGENO','Necesario para respirar'),
 (6,'FLUOR','Muy reactivo y presente en pastas dentales'),
 (6,'NEON','Gas usado en luces brillantes'),
 (6,'SODIO','Reacciona con el agua violentamente'),
 (6,'MAGNESIO','Arde con luz intensa'),
 (6,'ALUMINIO','Metal ligero muy utilizado'),
 (6,'SILICIO','Base de los microchips'),
 (6,'FOSFORO','Brilla en la oscuridad'),
 (6,'AZUFRE','Tiene olor caracteristico'),
 (6,'CLORO','Usado para desinfectar agua'),
 (6,'ARGON','Gas noble muy estable'),
 (6,'POTASIO','Reacciona rapidamente con agua'),
 (6,'CALCIO','Importante para huesos'),
 (6,'HIERRO','Metal base del acero'),
 (6,'COBALTO','Usado en imanes y baterias'),
 (6,'NIQUEL','Usado en monedas'),
 (6,'COBRE','Buen conductor electrico'),
 (6,'ZINC','Protege contra la corrosion'),
 (6,'PLATA','Metal precioso brillante'),
 (6,'ORO','Metal precioso muy valioso'),
 (6,'MERCURIO','Metal liquido a temperatura ambiente'),
 (6,'PLOMO','Metal pesado y toxico'),
 (6,'URANIO','Usado en energia nuclear'),
 (6,'PLUTONIO','Elemento radiactivo artificial'),
 (6,'RADIO','Elemento altamente radiactivo'),
 (6,'RADON','Gas radiactivo natural'),
 (6,'TITANIO','Metal fuerte y ligero'),
 (6,'CROMO','Da brillo a metales'),
 (6,'MANGANESO','Usado en acero'),
 (6,'MOLIBDENO','Resiste altas temperaturas'),
 (6,'TUNGSTENO','Punto de fusion muy alto'),
 (6,'VANADIO','Se usa en aleaciones'),
 (6,'ESCANDIO','Metal poco comun'),
 (6,'GALIO','Se derrite con el calor de la mano'),
 (6,'GERMANIO','Usado en semiconductores'),
 (6,'ARSENICO','Elemento toxico conocido'),
 (6,'SELENIO','Usado en electronica'),
 (6,'BROMO','Liquido rojizo y toxico'),
 (6,'YODO','Usado como desinfectante'),
 (6,'KRIPTON','Gas noble poco reactivo'),
 (6,'XENON','Gas usado en luces especiales'),
 (6,'CESIO','Metal muy reactivo'),
 (6,'BARIO','Usado en radiografias'),
 (7,'ROSA','Flor muy asociada al amor'),
 (7,'TULIPAN','Flor muy conocida en jardines europeos'),
 (7,'GIRASOL','Sigue la luz del sol'),
 (7,'MARGARITA','Flor blanca con centro amarillo'),
 (7,'ORQUIDEA','Flor elegante y exotica'),
 (7,'CLAVEL','Flor muy usada en arreglos'),
 (7,'LIRIO','Flor asociada a pureza'),
 (7,'JAZMIN','Flor pequeña con aroma intenso'),
 (7,'DALIA','Flor muy popular en Mexico'),
 (7,'AZUCENA','Flor blanca muy fragante'),
 (7,'HORTENSIA','Flor en forma de racimo'),
 (7,'BUGAMBILIA','Planta trepadora de colores vivos'),
 (7,'NARCISO','Flor asociada a mitologia'),
 (7,'AMAPOLA','Flor roja muy llamativa'),
 (7,'CALENDULA','Flor anaranjada medicinal'),
 (7,'CAMELIA','Flor elegante y delicada'),
 (7,'GERANIO','Planta comun en balcones'),
 (7,'PETUNIA','Flor de colores variados'),
 (7,'MAGNOLIA','Flor grande y fragante'),
 (7,'VIOLETA','Flor pequena de tono morado'),
 (7,'LAVANDA','Planta aromatica relajante'),
 (7,'MENTA','Planta aromatica fresca'),
 (7,'ALBAHACA','Usada en cocina italiana'),
 (7,'ROMERO','Hierba aromatica comun'),
 (7,'TOMILLO','Planta usada en condimentos'),
 (7,'CILANTRO','Muy usado en cocina mexicana'),
 (7,'PEREJIL','Hierba verde decorativa'),
 (7,'BAMBU','Planta alta y flexible'),
 (7,'CACTUS','Planta de zonas deserticas'),
 (7,'HELECHO','Planta sin flores visible'),
 (7,'PALMA','Arbol tropical caracteristico'),
 (7,'PINO','Arbol de hoja perenne'),
 (7,'ROBLE','Arbol fuerte y longevo'),
 (7,'SAUCE','Arbol con ramas caidas'),
 (7,'CEDRO','Arbol aromatico y resistente'),
 (7,'ENCINO','Arbol comun en Mexico'),
 (7,'MANZANO','Arbol que da una fruta conocida'),
 (7,'NARANJO','Arbol frutal citrico'),
 (7,'LIMONERO','Arbol pequeño con frutos acidos'),
 (7,'OLIVO','Arbol asociado al aceite'),
 (7,'VID','Planta que produce uvas'),
 (7,'TRIGO','Planta base de muchos alimentos'),
 (7,'MAIZ','Cultivo muy importante en America'),
 (7,'ARROZ','Planta que crece en agua'),
 (7,'SOYA','Usada en productos alimenticios'),
 (7,'AVENA','Cereal comun en desayunos'),
 (7,'CAÑA','Planta de donde se obtiene azucar'),
 (7,'ALGODON','Planta usada en textiles'),
 (7,'TABACO','Planta usada en cigarrillos'),
 (7,'CAFETO','Planta que produce cafe'),
 (8,'MARTILLO','Se usa con fuerza para ajustar o fijar piezas'),
 (8,'DESTORNILLADOR','Gira pequeños elementos para asegurar piezas'),
 (8,'LLAVE','Ajusta o afloja uniones metalicas'),
 (8,'PINZAS','Sirven para sujetar sin tocar directamente'),
 (8,'TENAZAS','Aplican fuerza para doblar o cortar'),
 (8,'SERRUCHO','Divide materiales usando movimiento manual'),
 (8,'SIERRA','Corta con dientes repetitivos'),
 (8,'LIJADORA','Deja superficies mas suaves al contacto'),
 (8,'TALADRO','Perfora materiales con giro rapido'),
 (8,'PALA','Permite mover tierra o materiales sueltos'),
 (8,'PICO','Rompe superficies duras con impacto'),
 (8,'AZADON','Trabaja la tierra antes de sembrar'),
 (8,'CARRETILLA','Transporta carga con una sola rueda'),
 (8,'NIVEL','Indica si algo esta completamente recto'),
 (8,'METRO','Mide distancias en trabajos manuales'),
 (8,'CINTA','Se extiende para medir longitudes'),
 (8,'ESCUADRA','Ayuda a formar angulos precisos'),
 (8,'COMPAS','Traza figuras circulares'),
 (8,'BROCHA','Extiende liquidos sobre superficies'),
 (8,'RODILLO','Distribuye pintura de forma uniforme'),
 (8,'CUTTER','Realiza cortes finos en materiales ligeros'),
 (8,'NAVAJA','Herramienta pequeña para cortes variados'),
 (8,'MACHETE','Corta vegetacion con facilidad'),
 (8,'HACHA','Parte madera con golpes fuertes'),
 (8,'CUCHILLA','Realiza cortes precisos'),
 (8,'PRENSA','Mantiene piezas firmes mientras se trabaja'),
 (8,'SARGENTO','Sujeta materiales con presion ajustable'),
 (8,'ALICATE','Aprieta o corta cables'),
 (8,'PELACABLES','Retira recubrimientos sin dañar interior'),
 (8,'CAUTIN','Une materiales mediante calor'),
 (8,'PISTOLA','Aplica material liquido o caliente'),
 (8,'ENGRAPADORA','Fija elementos con pequeñas grapas'),
 (8,'REMACHADORA','Une piezas sin tornillos'),
 (8,'MULTIMETRO','Mide valores electricos'),
 (8,'FLEXOMETRO','Mide con cinta enrollable'),
 (8,'CALIBRADOR','Mide con gran precision'),
 (8,'TORNO','Da forma a piezas giratorias'),
 (8,'FRESADORA','Corta materiales con gran precision'),
 (8,'AMOLADORA','Desgasta superficies con disco giratorio'),
 (8,'ESMERIL','Afila y pule materiales'),
 (8,'BOMBA','Impulsa aire o liquidos'),
 (8,'COMPRESOR','Almacena aire a presion'),
 (8,'ASPIRADORA','Extrae suciedad mediante succion'),
 (8,'SOPLETE','Aplica calor intenso localizado'),
 (8,'CLAVADORA','Introduce fijaciones rapidamente'),
 (8,'DESARMADOR','Variante comun para tornillos'),
 (8,'LLAVEINGLESA','Se ajusta a distintos tamanos'),
 (8,'LLAVEALLEN','Encaja en tornillos especiales'),
 (8,'MARTILLOGOMA','Golpea sin dañar superficies'),
 (8,'CEPILLO','Alisa superficies de madera'),
 (9,'MESA','Superficie donde se apoyan cosas del dia a dia'),
 (9,'SILLA','Permite descansar sin acostarse'),
 (9,'SILLON','Mas amplio y comodo que su version individual'),
 (9,'CAMA','Lugar donde termina la jornada'),
 (9,'ALMOHADA','Suaviza el descanso de la cabeza'),
 (9,'COBIJA','Ayuda a conservar el calor al dormir'),
 (9,'ESPEJO','Devuelve la imagen de quien lo mira'),
 (9,'RELOJ','Marca el paso del tiempo'),
 (9,'LAMPARA','Ilumina espacios en ausencia de sol'),
 (9,'FOCO','Fuente de luz artificial en el techo'),
 (9,'VENTILADOR','Mueve el aire sin enfriarlo realmente'),
 (9,'TELEVISION','Muestra imagenes y sonido a distancia'),
 (9,'CONTROL','Permite manejar aparatos sin tocarlos'),
 (9,'RADIO','Transmite sonido sin necesidad de imagen'),
 (9,'REFRIGERADOR','Mantiene alimentos en baja temperatura'),
 (9,'MICROONDAS','Calienta comida en poco tiempo'),
 (9,'ESTUFA','Genera calor para cocinar'),
 (9,'HORNO','Encierra el calor para preparar alimentos'),
 (9,'LICUADORA','Convierte solidos en mezclas liquidas'),
 (9,'CAFETERA','Prepara una bebida muy popular al despertar'),
 (9,'TETERA','Calienta agua para infusiones'),
 (9,'VASO','Contiene liquidos para beber'),
 (9,'PLATO','Sostiene alimentos durante las comidas'),
 (9,'CUCHARA','Ayuda a llevar alimentos a la boca'),
 (9,'TENEDOR','Pincha para facilitar comer'),
 (9,'CUCHILLO','Divide alimentos con precision'),
 (9,'COLADOR','Separa solidos de liquidos'),
 (9,'SARTEN','Recipiente plano para cocinar'),
 (9,'OLLA','Contenedor profundo para hervir'),
 (9,'ESCURRIDOR','Deja salir el agua despues de lavar'),
 (9,'TRAPEADOR','Limpia superficies con humedad'),
 (9,'ESCOBA','Recoge polvo sin usar agua'),
 (9,'RECOGEDOR','Complementa a otro para juntar suciedad'),
 (9,'ASPIRADORA','Extrae polvo con succion'),
 (9,'CORTINA','Cubre ventanas y controla la luz'),
 (9,'PERSIANA','Regula entrada de luz desde la ventana'),
 (9,'ARMARIO','Guarda ropa u objetos personales'),
 (9,'CAJON','Espacio oculto dentro de un mueble'),
 (9,'PERCHERO','Sostiene prendas sin doblarlas'),
 (9,'PLANCHA','Alisa telas con calor'),
 (10,'GUITARRA','Se toca con cuerdas y manos'),
 (10,'PIANO','Teclas blancas y negras producen sonido'),
 (10,'VIOLIN','Se usa arco para hacer vibrar cuerdas'),
 (10,'CELLO','Similar al violin pero de mayor tamaño'),
 (10,'CONTRABAJO','El mas grande de su familia de cuerdas'),
 (10,'ARPA','Cuerdas verticales que se pulsan'),
 (10,'BAJO','Marca el ritmo grave en la musica'),
 (10,'BATERIA','Conjunto que marca el pulso musical'),
 (10,'TAMBOR','Produce sonido al ser golpeado'),
 (10,'TROMPETA','Instrumento de viento con sonido brillante'),
 (10,'TROMBON','Viento metalico con vara deslizante'),
 (10,'TUBA','El mas grave de los metales'),
 (10,'FLAUTA','Produce sonido al soplar por un orificio'),
 (10,'CLARINETE','Viento madera con lengueta simple'),
 (10,'OBOE','Sonido nasal y caracteristico'),
 (10,'FAGOT','Instrumento largo de sonido profundo'),
 (10,'SAXOFON','Muy usado en jazz'),
 (10,'ACORDEON','Se expande y contrae para sonar'),
 (10,'ARMONICA','Pequeno instrumento de viento'),
 (10,'MARIMBA','Teclas de madera golpeadas'),
 (10,'XILOFONO','Similar a la marimba pero mas agudo'),
 (10,'CAMPANA','Produce sonido al ser golpeada'),
 (10,'TRIANGULO','Metalico y de sonido agudo'),
 (10,'PANDERO','Se agita o golpea para sonar'),
 (10,'CASTAÑUELAS','Se tocan con las manos'),
 (10,'BONGO','Par de tambores pequenos'),
 (10,'CONGA','Tambor alto usado en ritmos latinos'),
 (10,'TIMBAL','Tambor metalico afinado'),
 (10,'GUIRO','Se raspa para producir sonido'),
 (10,'CLAVES','Dos piezas que se golpean entre si'),
 (10,'ZAMPOÑA','Instrumento andino de tubos'),
 (10,'QUENA','Flauta tradicional sudamericana'),
 (10,'BALALAIKA','Instrumento ruso de cuerdas'),
 (10,'SITAR','Instrumento de la musica india'),
 (10,'BANJO','Muy usado en musica country'),
 (10,'MANDOLINA','Pequeno instrumento de cuerdas'),
 (10,'UKELELE','Version pequena de guitarra'),
 (10,'ORGANO','Similar al piano pero mas complejo'),
 (10,'SINTETIZADOR','Genera sonidos electronicos'),
 (10,'MELODICA','Se sopla y se presionan teclas'),
 (11,'NETFLIX','Ofrece series y peliculas bajo demanda'),
 (11,'YOUTUBE','Plataforma donde cualquiera puede subir videos'),
 (11,'FACEBOOK','Red social para conectar con amigos'),
 (11,'INSTAGRAM','Comparte imagenes y momentos'),
 (11,'WHATSAPP','Permite enviar mensajes al instante'),
 (11,'TWITTER','Mensajes cortos y tendencias globales'),
 (11,'TIKTOK','Videos breves con musica y efectos'),
 (11,'GOOGLE','Herramienta principal para buscar en internet'),
 (11,'MICROSOFT','Empresa detras de sistemas operativos populares'),
 (11,'APPLE','Conocida por dispositivos con diseno distintivo'),
 (11,'SAMSUNG','Fabricante de tecnologia muy extendido'),
 (11,'HUAWEI','Marca asiatica de telefonia'),
 (11,'XIAOMI','Tecnologia accesible y popular'),
 (11,'SONY','Reconocida en audio y videojuegos'),
 (11,'NINTENDO','Empresa ligada a consolas clasicas'),
 (11,'PLAYSTATION','Consola de videojuegos muy famosa'),
 (11,'XBOX','Competencia directa en videojuegos'),
 (11,'LENOVO','Fabricante de computadoras portatiles'),
 (11,'HP','Marca comun en impresoras y laptops'),
 (11,'DELL','Computadoras para trabajo y hogar'),
 (11,'ASUS','Equipo de computo y componentes'),
 (11,'ACER','Tecnologia accesible para usuarios'),
 (11,'INTEL','Procesadores dentro de muchas maquinas'),
 (11,'AMD','Alternativa en procesamiento digital'),
 (11,'NVIDIA','Especialista en graficos'),
 (11,'ADIDAS','Ropa y calzado deportivo'),
 (11,'NIKE','Marca deportiva con gran presencia'),
 (11,'PUMA','Competencia en ropa deportiva'),
 (11,'REEBOK','Otra marca del mundo fitness'),
 (11,'ZARA','Moda rapida en todo el mundo'),
 (11,'HNM','Ropa accesible de tendencia'),
 (11,'LEVIS','Conocida por sus pantalones de mezclilla'),
 (11,'GUCCI','Moda de lujo reconocida'),
 (11,'PRADA','Marca exclusiva italiana'),
 (11,'VERSACE','Estilo llamativo y lujoso'),
 (11,'MCDONALDS','Cadena global de comida rapida'),
 (11,'BURGERKING','Otra opcion de hamburguesas'),
 (11,'KFC','Especializada en pollo frito'),
 (11,'SUBWAY','Sandwiches preparados al momento'),
 (11,'DOMINOS','Entrega pizzas rapidamente'),
 (11,'PIZZAHUT','Cadena conocida por sus pizzas'),
 (11,'STARBUCKS','Bebidas calientes para comenzar el dia'),
 (11,'NESCAFE','Cafe instantaneo muy popular'),
 (11,'COCACOLA','Bebida oscura muy famosa'),
 (11,'PEPSI','Competencia directa de la anterior'),
 (11,'CORONA','Bebida mexicana reconocida mundialmente'),
 (11,'MODELO','Otra bebida tradicional mexicana'),
 (11,'BIMBO','Pan presente en muchos hogares'),
 (11,'SABRITAS','Botanas crujientes en bolsa'),
 (11,'BARCEL','Otra marca de snacks'),
 (11,'LALA','Productos derivados de la leche'),
 (11,'ALPURA','Competencia en productos lacteos'),
 (11,'DANONE','Yogur y productos similares'),
 (11,'NESTLE','Gran empresa de alimentos'),
 (11,'KELLOGGS','Cereales para el desayuno'),
 (11,'GAMESA','Galletas muy comunes'),
 (11,'OREO','Galleta oscura con relleno blanco'),
 (11,'RAPPI','Entrega comida a domicilio'),
 (11,'UBER','Servicio de transporte por aplicacion'),
 (11,'DIDI','Alternativa de movilidad urbana'),
 (11,'MERCADOLIBRE','Compra y vende en linea'),
 (11,'AMAZON','Tienda global en internet'),
 (11,'EBAY','Ventas en linea con subastas'),
 (11,'PAYPAL','Pagos digitales seguros'),
 (11,'SPOTIFY','Musica en streaming'),
 (11,'DISNEY','Empresa de entretenimiento familiar'),
 (11,'PIXAR','Animacion con historias emotivas'),
 (11,'TOYOTA','Fabricante de autos japones'),
 (11,'NISSAN','Marca automotriz muy extendida'),
 (11,'FORD','Automoviles de origen estadounidense'),
 (12,'MEXICO','Famoso por su gastronomia y cultura'),
 (12,'CANADA','Pais al norte con clima frio'),
 (12,'BRASIL','El mas grande de Sudamerica'),
 (12,'ARGENTINA','Reconocido por su futbol y tango'),
 (12,'CHILE','Pais largo entre cordillera y mar'),
 (12,'PERU','Hogar de una antigua civilizacion'),
 (12,'COLOMBIA','Famoso por su cafe'),
 (12,'VENEZUELA','Rico en recursos naturales'),
 (12,'URUGUAY','Pequeño pero con alta calidad de vida'),
 (12,'PARAGUAY','Pais sin salida al mar'),
 (12,'BOLIVIA','Con altiplanos elevados'),
 (12,'ECUADOR','Cruzado por la linea imaginaria'),
 (12,'CUBA','Isla del Caribe con historia unica'),
 (12,'JAMAICA','Isla conocida por su musica'),
 (12,'PANAMA','Une dos grandes oceanos'),
 (12,'COSTARICA','Destino ecoturistico muy popular'),
 (12,'NICARAGUA','Tiene grandes lagos'),
 (12,'HONDURAS','Pais centroamericano con historia maya'),
 (12,'GUATEMALA','Cultura maya muy presente'),
 (12,'ESPAÑA','Pais europeo de lengua compartida'),
 (12,'FRANCIA','Conocido por su gastronomia y arte'),
 (12,'ITALIA','Famoso por su cocina y arquitectura'),
 (12,'ALEMANIA','Potencia industrial europea'),
 (12,'PORTUGAL','Pais costero de Europa occidental'),
 (12,'INGLATERRA','Parte del Reino Unido'),
 (12,'IRLANDA','Isla verde del norte'),
 (12,'NORUEGA','Fiordos y paisajes naturales'),
 (12,'SUECIA','Pais nordico muy desarrollado'),
 (12,'FINLANDIA','Conocido por su educacion'),
 (12,'DINAMARCA','Pais pequeño y moderno'),
 (12,'HOLANDA','Famoso por sus tulipanes'),
 (12,'BELGICA','Conocido por su chocolate'),
 (12,'SUIZA','Neutralidad y montañas'),
 (12,'AUSTRIA','Pais alpino de musica clasica'),
 (12,'POLONIA','Pais europeo con historia compleja'),
 (12,'GRECIA','Cuna de civilizaciones antiguas'),
 (12,'TURQUIA','Puente entre dos continentes'),
 (12,'RUSIA','El pais mas grande del mundo'),
 (12,'CHINA','Muy poblado y antiguo'),
 (12,'JAPON','Tecnologia y tradicion'),
 (12,'INDIA','Gran diversidad cultural'),
 (12,'PAKISTAN','Vecino de India con historia compartida'),
 (12,'IRAN','Pais de Oriente Medio con historia antigua'),
 (12,'ISRAEL','Region con gran importancia religiosa'),
 (12,'EGIPTO','Famoso por sus piramides'),
 (12,'AUSTRALIA','Pais y continente al mismo tiempo'),
 (12,'MARRUECOS','Pais africano con mercados tradicionales'),
 (12,'SINGAPUR','Ciudad estado muy moderna'),
 (12,'MALASIA','Pais del sudeste asiatico tropical'),
 (12,'INDONESIA','Archipielago con miles de islas'),
 (13,'SHREK','Ogro verde que vive en un pantano'),
 (13,'TITANIC','Historia romantica en un barco famoso'),
 (13,'BATMAN','Heroe oscuro de ciudad nocturna'),
 (13,'SUPERMAN','Vuela y tiene gran fuerza'),
 (13,'SPIDERMAN','Trepa muros y lanza telarañas'),
 (13,'AVATAR','Ambientada en un mundo azul alienigena'),
 (13,'FROZEN','Reina con poderes de hielo'),
 (13,'COCO','Viaje musical relacionado con tradiciones'),
 (13,'MOANA','Aventura en el oceano con una joven'),
 (13,'ENCANTO','Familia con habilidades especiales'),
 (13,'MULAN','Guerrera que oculta su identidad'),
 (13,'ALADDIN','Joven que encuentra una lampara especial'),
 (13,'DUMBO','Elefante que puede volar'),
 (13,'BAMBI','Crecimiento de un venado en el bosque'),
 (13,'CARS','Autos que compiten entre si'),
 (13,'UP','Casa que vuela con globos'),
 (13,'SOUL','Explora el sentido de la vida y musica'),
 (13,'LUCA','Amistad en un pueblo costero'),
 (13,'JOKER','Historia de un villano caotico'),
 (13,'VENOM','Ser oscuro que se une a un humano'),
 (13,'GLADIADOR','Combate en la antigua Roma'),
 (13,'ROCKY','Boxeador que lucha por superarse'),
 (13,'CREED','Continuacion de una historia de boxeo'),
 (13,'MATRIX','Realidad cuestionada por una simulacion'),
 (13,'INCEPTION','Sueños dentro de sueños'),
 (13,'INTERSTELLAR','Viaje espacial en busca de futuro'),
 (13,'GRAVITY','Supervivencia en el espacio'),
 (13,'ALIEN','Criatura peligrosa fuera de la Tierra'),
 (13,'PREDATOR','Cazador de otro mundo'),
 (13,'TRANSFORMERS','Robots que cambian de forma'),
 (13,'MINIONS','Pequeños ayudantes amarillos'),
 (13,'MADAGASCAR','Animales fuera de su habitat'),
 (13,'ICEAGE','Animales en la era de hielo'),
 (13,'HULK','Se vuelve mas fuerte al enojarse'),
 (13,'THOR','Dios con un martillo poderoso'),
 (13,'DEADPOOL','Antiheroe con humor irreverente'),
 (13,'HARRYPOTTER','Joven mago en escuela especial'),
 (13,'JURASSICPARK','Criaturas prehistoricas vuelven a la vida'),
 (13,'KINGKONG','Gigante simio en ciudad moderna'),
 (13,'JUMANJI','Juego que vuelve real lo imposible'),
 (13,'TARZAN','Hombre criado en la selva'),
 (13,'HERCULES','Fuerza extraordinaria desde joven'),
 (13,'PIRATAS','Aventuras en el mar con tesoros'),
 (13,'ZORRO','Heroe enmascarado con espada'),
 (13,'ROBINHOOD','Roba a ricos para ayudar a pobres'),
 (13,'TINTIN','Reportero que vive grandes aventuras'),
 (13,'ENREDADOS','Cabello magico con gran longitud'),
 (13,'VALIENTE','Princesa arquera que desafia tradiciones'),
 (13,'ONWARD','Hermanos buscan magia en mundo moderno'),
 (15,'MEDICO','Trabaja con la salud de las personas'),
 (15,'ENFERMERO','Apoya en el cuidado de pacientes'),
 (15,'DENTISTA','Se enfoca en la salud bucal'),
 (15,'PSICOLOGO','Ayuda a comprender la mente'),
 (15,'VETERINARIO','Atiende animales enfermos'),
 (15,'FARMACEUTICO','Maneja medicamentos y recetas'),
 (15,'INGENIERO','Resuelve problemas tecnicos complejos'),
 (15,'ARQUITECTO','Disena espacios habitables'),
 (15,'ALBAÑIL','Construye estructuras manualmente'),
 (15,'CARPINTERO','Trabaja principalmente con madera'),
 (15,'ELECTRICISTA','Se encarga de instalaciones de energia'),
 (15,'PLOMERO','Soluciona problemas de agua en casa'),
 (15,'MECANICO','Repara maquinas y vehiculos'),
 (15,'SOLDADOR','Une piezas usando calor'),
 (15,'HERRERO','Moldea metal con herramientas'),
 (15,'PROGRAMADOR','Escribe codigo para sistemas'),
 (15,'DISEÑADOR','Crea elementos visuales'),
 (15,'FOTOGRAFO','Captura momentos con una camara'),
 (15,'CAMAROGRAFO','Registra video en movimiento'),
 (15,'PERIODISTA','Informa sobre hechos actuales'),
 (15,'ESCRITOR','Crea historias o textos'),
 (15,'EDITOR','Revisa y mejora contenido'),
 (15,'MAESTRO','Enseña en el aula'),
 (15,'PROFESOR','Imparte conocimiento especializado'),
 (15,'ABOGADO','Defiende casos legales'),
 (15,'JUEZ','Toma decisiones en juicios'),
 (15,'POLICIA','Mantiene el orden publico'),
 (15,'BOMBERO','Actua en situaciones de emergencia'),
 (15,'MILITAR','Forma parte de fuerzas armadas'),
 (15,'PILOTO','Opera aeronaves'),
 (15,'AZAFATA','Asiste durante vuelos'),
 (15,'CONDUCTOR','Transporta personas o carga'),
 (15,'TAXISTA','Lleva pasajeros en la ciudad'),
 (15,'CHOFER','Maneja vehiculos para terceros'),
 (15,'COCINERO','Prepara alimentos en cocina'),
 (15,'CHEF','Dirige la preparacion culinaria'),
 (15,'MESERO','Atiende a clientes en restaurantes'),
 (15,'BARISTA','Especialista en bebidas de cafe'),
 (15,'PANADERO','Elabora productos horneados'),
 (15,'CARNICERO','Trabaja con productos de origen animal'),
 (15,'PESCADOR','Obtiene recursos del agua'),
 (15,'AGRICULTOR','Cultiva la tierra'),
 (15,'GANADERO','Cria animales para produccion'),
 (15,'VENDEDOR','Ofrece productos o servicios'),
 (15,'CAJERO','Maneja cobros en negocios'),
 (15,'GERENTE','Coordina equipos de trabajo'),
 (15,'ADMINISTRADOR','Organiza recursos y procesos'),
 (15,'CONTADOR','Gestiona numeros y finanzas'),
 (15,'ECONOMISTA','Analiza sistemas financieros'),
 (15,'ACTOR','Interpreta personajes en escena'),
 (14,'CAMISA','Prenda superior con botones'),
 (14,'PANTALON','Cubre ambas piernas'),
 (14,'SHORT','Version corta del pantalon'),
 (14,'FALDA','Prenda inferior sin dividir piernas'),
 (14,'VESTIDO','Prenda completa en una sola pieza'),
 (14,'CHAQUETA','Se usa sobre otra prenda'),
 (14,'ABRIGO','Protege del frio intenso'),
 (14,'SUDADERA','Comoda y de uso casual'),
 (14,'SUETER','Tejido para clima fresco'),
 (14,'PLAYERA','Prenda ligera de uso diario'),
 (14,'BLUSA','Similar a camisa pero mas ligera'),
 (14,'TOP','Prenda corta para la parte superior'),
 (14,'TRAJE','Conjunto formal de varias piezas'),
 (14,'CORBATA','Accesorio que cuelga del cuello'),
 (14,'PAPILLON','Alternativa pequeña a la corbata'),
 (14,'CINTURON','Ajusta prendas en la cintura'),
 (14,'CALCETINES','Cubren los pies dentro del calzado'),
 (14,'MEDIAS','Version larga y delgada para piernas'),
 (14,'PANTIMEDIAS','Cubren piernas completas'),
 (14,'ZAPATOS','Calzado cerrado formal'),
 (14,'TENIS','Calzado comodo para uso diario'),
 (14,'BOTAS','Cubren mas arriba del tobillo'),
 (14,'SANDALIAS','Calzado abierto y fresco'),
 (14,'GORRA','Cubre la cabeza con visera'),
 (14,'SOMBRERO','Protege del sol con ala amplia'),
 (14,'BUFANDA','Se coloca alrededor del cuello'),
 (14,'GUANTES','Cubren y protegen las manos'),
 (14,'PIJAMA','Se usa al dormir'),
 (14,'BATA','Prenda suelta para casa'),
 (14,'CHAMARRA','Prenda exterior para clima frio'),
 (14,'IMPERMEABLE','Evita mojarse con la lluvia'),
 (14,'OVEROL','Prenda de una sola pieza de trabajo'),
 (14,'UNIFORME','Identifica a un grupo o profesion'),
 (14,'TRAJEBANO','Se usa para nadar'),
 (14,'PANTUFLAS','Calzado para estar en casa'),
 (16,'SUPERMAN','Fuerza y vuelo desde otro mundo'),
 (16,'BATMAN','Combate el crimen sin poderes'),
 (16,'SPIDERMAN','Se mueve entre edificios con agilidad'),
 (16,'IRONMAN','Armadura avanzada con tecnologia'),
 (16,'CAPITANAMERICA','Escudo y valores firmes'),
 (16,'THOR','Poder ligado a un arma mitica'),
 (16,'HULK','Mientras mas se altera, mas fuerte se vuelve'),
 (16,'BLACKWIDOW','Habilidad y precision en combate'),
 (16,'HAWKEYE','Nunca falla cuando apunta'),
 (16,'ANTMAN','Cambia de tamano a voluntad'),
 (16,'WASP','Pequena pero muy veloz en el aire'),
 (16,'VISION','Integra tecnologia y poder especial'),
 (16,'SCARLETWITCH','Manipula la realidad a su manera'),
 (16,'DOCTORSTRANGE','Domina artes fuera de lo comun'),
 (16,'BLACKPANTHER','Protector con habilidades mejoradas'),
 (16,'CAPITANAMARVEL','Energia y vuelo en gran escala'),
 (16,'DEADPOOL','Rompe reglas incluso fuera de la historia'),
 (16,'WOLVERINE','Se regenera y tiene garras'),
 (16,'STORM','Controla el clima a voluntad'),
 (16,'CYCLOPE','Lanza energia desde la mirada'),
 (16,'ROGUE','Toma habilidades al tocar'),
 (16,'GAMBIT','Convierte objetos en energia'),
 (16,'NIGHTCRAWLER','Se mueve instantaneamente entre lugares'),
 (16,'ICEMAN','Genera hielo y frio extremo'),
 (16,'DAREDEVIL','Percibe el entorno sin ver'),
 (16,'PUNISHER','Justicia directa sin reglas'),
 (16,'LINTERNAVERDE','Crea con energia de su anillo'),
 (16,'FLASH','Corre a velocidades imposibles'),
 (16,'AQUAMAN','Gobierna bajo el mar'),
 (16,'MUJERMARAVILLA','Fuerza y lazo de verdad'),
 (16,'CYBORG','Mitad humano mitad maquina'),
 (16,'SHAZAM','Poder magico con una palabra'),
 (16,'SPAWN','Guerrero con origen oscuro'),
 (16,'HELLBOY','Criatura con fuerza sobrenatural'),
 (16,'RYU','Maestro del combate con energia interior'),
 (16,'CHUNLI','Rapidez y tecnica en combate'),
 (16,'AKUMA','Poder extremo y estilo agresivo'),
 (16,'MEGAMAN','Armas que cambian segun enemigo'),
 (16,'ZERO','Espada y precision en batalla'),
 (16,'STRIDER','Ninja futurista muy habil');
COMMIT;
