BEGIN TRANSACTION;
UPDATE sqlite_sequence SET seq = 17 WHERE name = 'categorias';
UPDATE sqlite_sequence SET seq = 762 WHERE name = 'palabras';
UPDATE categorias SET nombre = 'ROPA/ACCESORIOS' WHERE id_categoria = 14;
UPDATE categorias SET nombre = 'BOTANICA' WHERE id_categoria = 7;

INSERT OR IGNORE INTO categorias (nombre, url_icono) VALUES
('NOMBRES','cat_nombres.png'),
('CIUDADES','cat_ciudades.png'),
('ANATOMIA','cat_cuerpo.png'),
('MITOLOGIA','cat_mitologia.png'),
('TECNOLOGIA','cat_tecnologia.png'),
('ASTRONOMIA','cat_astronomia.png'),
('NATURALEZA','cat_naturaleza.png'),
('PERSONAJES','cat_personajes.png'),
('EDIFICIOS','cat_edificios.png'),
('JUEGOS/JUGUETES','cat_juegos.png');
COMMIT;
BEGIN TRANSACTION;
INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(17, 'TSURU', 'Auto sedan economico clasico en Mexico'),
(17, 'GOLF', 'Hatchback aleman muy popular y reconocido'),
(17, 'SENTRA', 'Sedan compacto clasico de marca Nissan'),
(17, 'COROLLA', 'El auto mas vendido del mundo'),
(17, 'CIVIC', 'Compacto japones famoso por su durabilidad'),
(17, 'JETTA', 'Sedan aleman clasico muy querido'),
(17, 'MUSTANG', 'Deportivo americano famoso de marca Ford'),
(17, 'CAMARO', 'Deportivo Chevrolet rival directo del Mustang'),
(17, 'BEETLE', 'Auto clasico con forma de escarabajo'),
(17, 'AVEO', 'Subcompacto economico comun en la ciudad'),
(17, 'MARCH', 'Auto compacto y agil para ciudad'),
(17, 'CHEVY', 'Pequeño auto economico popular de Chevrolet'),
(17, 'VERSA', 'Subcompacto moderno y amplio de Nissan'),
(17, 'ACCORD', 'Sedan mediano elegante de la Honda'),
(17, 'CAMRY', 'Sedan mediano muy confiable de Toyota'),
(17, 'FIESTA', 'Hatchback subcompacto clasico de marca Ford'),
(17, 'FOCUS', 'Auto compacto global de marca Ford'),
(17, 'YARIS', 'Auto pequeno y muy eficiente Toyota'),
(17, 'RIO', 'Subcompacto moderno de la marca Kia'),
(17, 'FORTE', 'Sedan compacto elegante de marca Kia'),
(17, 'SWIFT', 'Hatchback ligero y muy deportivo Suzuki'),
(17, 'SPARK', 'Pequeno auto urbano economico de Chevrolet'),
(17, 'MATIZ', 'Auto supercompacto ideal para la ciudad'),
(17, 'POINTER', 'Hatchback economico muy clasico en Mexico'),
(17, 'ALTIMA', 'Sedan de tamaño mediano de Nissan'),
(17, 'MAXIMA', 'Sedan deportivo de lujo de Nissan'),
(17, 'CHARGER', 'Deportivo potente americano de cuatro puertas'),
(17, 'CHALLENGER', 'Auto deportivo clasico muscle car Dodge'),
(17, 'CORVETTE', 'Deportivo de alto rendimiento de Chevrolet'),
(17, 'SONIC', 'Subcompacto moderno de la marca Chevrolet'),
(17, 'CRUZE', 'Sedan compacto global de marca Chevrolet'),
(17, 'IBIZA', 'Hatchback juvenil popular de marca Seat'),
(17, 'LEON', 'Hatchback deportivo moderno de marca Seat'),
(17, 'TOLEDO', 'Sedan sobrio y espacioso de Seat'),
(17, 'MEGANE', 'Auto compacto famoso de la Renault'),
(17, 'CLIO', 'Hatchback subcompacto muy popular de Renault'),
(17, 'KWID', 'Auto urbano compacto con estilo SUV'),
(17, 'SANDERO', 'Hatchback amplio y practico de Renault'),
(17, 'LOGAN', 'Sedan economico clasico de marca Renault'),
(17, 'PRIUS', 'Auto hibrido mas famoso del mundo'),
(17, 'FIT', 'Subcompacto con gran espacio interior Honda'),
(17, 'CITY', 'Sedan subcompacto muy elegante de Honda'),
(17, 'POLO', 'Hatchback compacto sobrio de la Volkswagen'),
(17, 'BORA', 'Sedan aleman elegante predecesor del Jetta'),
(17, 'CORSAR', 'Sedan clasico ochentero de la Volkswagen'),
(17, 'ATLANTIC', 'Auto clasico ochentero derivado del Golf'),
(17, 'CARIBE', 'Nombre mexicano para Golf primera generacion'),
(17, 'BRASILIA', 'Auto clasico familiar con el motor trasero'),
(17, 'SAFARI', 'Auto clasico todoterreno de la Volkswagen'),
(17, 'VALIANT', 'Auto clasico americano de gran tamano'),
(17, 'MAVERICK', 'Auto clasico compacto de la Ford'),
(17, 'TOPAZ', 'Sedan clasico noventero de la Ford'),
(17, 'SPIRIT', 'Sedan noventero muy conocido de Dodge'),
(17, 'SHADOW', 'Auto compacto noventero de la Dodge'),
(17, 'NEON', 'Compacto noventero famoso de marca Dodge'),
(17, 'STRATUS', 'Sedan mediano muy elegante de Dodge'),
(17, 'LANCER', 'Sedan compacto deportivo de la Mitsubishi'),
(17, 'IMPREZA', 'Auto compacto con traccion cuatro ruedas'),
(17, 'MALIBU', 'Sedan mediano clasico de la Chevrolet'),
(17, 'CAVALIER', 'Sedan compacto popular de la Chevrolet'),
(18, 'GUADALUPE', 'Nombre muy comun en Mexico para ambos sexos'),
(18, 'FERNANDO', 'Nombre masculino comun de origen germanico muy popular'),
(18, 'SANTIAGO', 'Nombre masculino muy popular en toda Latinoamerica'),
(18, 'MATEO', 'Nombre de origen hebreo muy popular en ninos'),
(18, 'VALENTINA', 'Nombre femenino popular que transmite fuerza y salud'),
(18, 'SOFIA', 'Nombre femenino clasico que significa sabiduria'),
(18, 'REGINA', 'Nombre femenino muy usado en Mexico significa reina'),
(18, 'CAMILA', 'Nombre femenino de origen latin bastante popular'),
(18, 'SEBASTIAN', 'Nombre masculino de origen griego muy comun'),
(18, 'ALEJANDRO', 'Nombre clasico masculino que significa protector del hombre'),
(18, 'VALERIA', 'Nombre femenino tradicional y elegante en la region'),
(18, 'XIMENA', 'Nombre femenino clasico con grafia muy mexicana'),
(18, 'MARIANA', 'Nombre femenino compuesto clasico en la cultura hispana'),
(18, 'VICTORIA', 'Nombre femenino clasico que evoca el triunfo'),
(18, 'DANIELA', 'Nombre popular en Mexico de origen hebreo'),
(18, 'EMILIANO', 'Nombre masculino muy ligado a la historia mexicana'),
(18, 'LEONARDO', 'Nombre masculino fuerte de origen germanico'),
(18, 'DIEGO', 'Nombre clasico masculino famoso en la historia hispana'),
(18, 'GAEL', 'Nombre masculino corto y popular en Mexico'),
(18, 'RODRIGO', 'Nombre de origen germanico tradicional en la region'),
(18, 'CARLOS', 'Nombre tradicional masculino muy comun en Mexico'),
(18, 'JOSUE', 'Nombre masculino de tradicion biblica y bastante comun'),
(18, 'GABRIEL', 'Nombre de origen hebreo con gran tradicion hispana'),
(18, 'ADRIAN', 'Nombre clasico latino muy difundido en la region'),
(18, 'JAVIER', 'Nombre masculino de origen vasco muy tradicional'),
(18, 'RICARDO', 'Nombre masculino clasico que evoca poder y liderazgo'),
(18, 'MAURICIO', 'Nombre masculino tradicional de origen latino'),
(18, 'ROBERTO', 'Nombre masculino clasico popular en familias hispanas'),
(18, 'HECTOR', 'Nombre masculino de origen griego muy tradicional'),
(18, 'EDUARDO', 'Nombre clasico muy comun en toda Latinoamerica'),
(18, 'SERGIO', 'Nombre masculino tradicional de origen latino'),
(18, 'ARTURO', 'Nombre clasico masculino de gran tradicion'),
(18, 'BENJAMIN', 'Nombre masculino biblico muy popular actualmente'),
(18, 'SAMUEL', 'Nombre masculino de origen hebreo bastante comun'),
(18, 'JOAQUIN', 'Nombre clasico masculino de gran tradicion en Mexico'),
(18, 'EMILIO', 'Nombre masculino tradicional que denota amabilidad'),
(18, 'TOMAS', 'Nombre tradicional masculino de origen arameo'),
(18, 'NICOLAS', 'Nombre de origen griego muy popular en ninos'),
(18, 'MATIAS', 'Nombre masculino corto muy popular en la region'),
(18, 'PABLO', 'Nombre clasico de origen latino muy extendido'),
(18, 'LUCIA', 'Nombre femenino clasico que significa luz radiante'),
(18, 'FERNANDA', 'Nombre femenino muy usado en toda Latinoamerica'),
(18, 'XOCHITL', 'Nombre femenino de origen nahuatl significa flor'),
(18, 'ITZEL', 'Nombre femenino de origen maya con gran tradicion'),
(18, 'CITLALI', 'Nombre femenino de origen nahuatl significa estrella'),
(18, 'YARETZI', 'Nombre femenino de origen indigena muy bonito'),
(18, 'ALONDRA', 'Nombre femenino clasico que evoca a un ave'),
(18, 'MONTSERRAT', 'Nombre femenino muy popular en familias mexicanas'),
(18, 'PAOLA', 'Nombre femenino de origen latino bastante comun'),
(18, 'ANDREA', 'Nombre popular usado frecuentemente para mujeres'),
(18, 'NATALIA', 'Nombre femenino clasico que evoca la navidad'),
(18, 'VANESSA', 'Nombre femenino muy popular desde los noventa'),
(18, 'JESSICA', 'Nombre femenino muy comun en jovenes de Mexico'),
(18, 'KARLA', 'Nombre femenino popular de origen germanico'),
(18, 'VERONICA', 'Nombre clasico femenino muy tradicional en Mexico'),
(18, 'PATRICIA', 'Nombre femenino tradicional en familias hispanas'),
(18, 'ROSA', 'Nombre femenino clasico que evoca una flor'),
(18, 'LETICIA', 'Nombre femenino tradicional de origen latino'),
(18, 'GABRIELA', 'Nombre femenino muy comun de origen hebreo'),
(18, 'BEATRIZ', 'Nombre clasico femenino que evoca felicidad'),
(18, 'YAZMIN', 'Nombre femenino muy comun inspirado en una flor'),
(18, 'LUPITA', 'Nombre femenino diminutivo muy afectuoso en Mexico'),
(18, 'PANCHO', 'Nombre clasico masculino muy tradicional en el pais'),
(18, 'PEPE', 'Nombre corto muy popular para referirse a Jose'),
(18, 'NACHO', 'Nombre popular de origen afectuoso en Mexico'),
(18, 'CUAUHTEMOC', 'Nombre masculino historico de origen nahuatl'),
(18, 'MOCTEZUMA', 'Nombre masculino de origen azteca con gran historia'),
(18, 'IXCHEL', 'Nombre femenino de origen maya muy conocido'),
(18, 'NAYELI', 'Nombre femenino de origen zapoteco significa te quiero'),
(18, 'SURISADAI', 'Nombre femenino de origen biblico comun en Mexico'),
(18, 'ESTEFANIA', 'Nombre femenino clasico de origen griego'),
(18, 'REBECA', 'Nombre femenino de tradicion biblica muy comun'),
(18, 'DIANA', 'Nombre femenino clasico de origen mitologico'),
(18, 'SARA', 'Nombre femenino de origen hebreo muy popular'),
(18, 'ELENA', 'Nombre clasico femenino que significa antorcha brillante'),
(18, 'LAURA', 'Nombre clasico de gran tradicion en la region'),
(18, 'LIDIA', 'Nombre femenino tradicional de origen griego'),
(18, 'ALICIA', 'Nombre tradicional femenino muy comun en la region'),
(18, 'MARTHA', 'Nombre clasico femenino muy tradicional en Mexico'),
(18, 'NORMA', 'Nombre femenino tradicional de origen latino'),
(18, 'GLORIA', 'Nombre clasico femenino que evoca un sentimiento alto'),
(18, 'SILVIA', 'Nombre tradicional femenino muy popular en Mexico'),
(18, 'TERESA', 'Nombre femenino tradicional de gran arraigo hispano'),
(18, 'MIGUEL', 'Nombre masculino clasico muy comun en Mexico'),
(18, 'JUAN', 'Nombre masculino mas tradicional en la cultura hispana'),
(18, 'JOSE', 'Nombre masculino clasico de inmensa tradicion hispana'),
(18, 'PEDRO', 'Nombre masculino tradicional de origen biblico'),
(18, 'JESUS', 'Nombre masculino clasico de enorme tradicion en Mexico'),
(18, 'ANGEL', 'Nombre masculino muy popular que denota pureza');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(19, 'AGUASCALIENTES', 'Capital del estado de Aguascalientes'),
(19, 'MEXICALI', 'Capital del estado de Baja California'),
(19, 'LAPAZ', 'Capital de Baja California Sur'),
(19, 'CAMPECHE', 'Capital historica del estado de Campeche'),
(19, 'SALTILLO', 'Capital del estado de Coahuila'),
(19, 'COLIMA', 'Capital del estado de Colima'),
(19, 'TUXTLA', 'Capital del estado de Chiapas'),
(19, 'CHIHUAHUA', 'Capital del estado de Chihuahua'),
(19, 'DURANGO', 'Capital del estado de Durango'),
(19, 'GUANAJUATO', 'Capital colonial del estado de Guanajuato'),
(19, 'CHILPANCINGO', 'Capital del estado de Guerrero'),
(19, 'PACHUCA', 'Capital minera del estado de Hidalgo'),
(19, 'GUADALAJARA', 'Capital tapatia del estado de Jalisco'),
(19, 'TOLUCA', 'Capital fria del Estado de Mexico'),
(19, 'MORELIA', 'Capital colonial del estado de Michoacan'),
(19, 'CUERNAVACA', 'Capital de la eterna primavera en Morelos'),
(19, 'TEPIC', 'Capital del estado de Nayarit'),
(19, 'MONTERREY', 'Capital industrial del estado de Nuevo Leon'),
(19, 'OAXACA', 'Capital cultural del estado de Oaxaca'),
(19, 'PUEBLA', 'Capital gastronomica del estado de Puebla'),
(19, 'QUERETARO', 'Capital historica del estado de Queretaro'),
(19, 'CHETUMAL', 'Capital del estado de Quintana Roo'),
(19, 'POTOSI', 'Capital del estado San Luis Potosi'),
(19, 'CULIACAN', 'Capital del estado de Sinaloa'),
(19, 'HERMOSILLO', 'Capital del estado de Sonora'),
(19, 'VILLAHERMOSA', 'Capital del estado de Tabasco'),
(19, 'VICTORIA', 'Capital del estado de Tamaulipas'),
(19, 'TLAXCALA', 'Capital del estado de Tlaxcala'),
(19, 'XALAPA', 'Capital universitaria del estado de Veracruz'),
(19, 'MERIDA', 'Capital blanca del estado de Yucatan'),
(19, 'ZACATECAS', 'Capital colonial y minera de Zacatecas'),
(19, 'CANCUN', 'Famosa ciudad turistica del caribe mexicano'),
(19, 'ACAPULCO', 'Famoso puerto turistico del estado Guerrero'),
(19, 'TIJUANA', 'Ciudad fronteriza muy famosa de Mexico'),
(19, 'LEON', 'Ciudad industrial famosa por el cuero'),
(19, 'TORREON', 'Ciudad importante de la comarca lagunera'),
(19, 'VERACRUZ', 'Puerto historico muy importante de Mexico'),
(19, 'MAZATLAN', 'Puerto turistico famoso del pacifico mexicano'),
(19, 'CELAYA', 'Ciudad de Guanajuato famosa por cajeta'),
(19, 'FRESNILLO', 'Ciudad importante minera del estado Zacatecas'),
(19, 'IRAPUATO', 'Ciudad de Guanajuato famosa por fresas'),
(19, 'ORIZABA', 'Pueblo magico cerca del pico alto'),
(19, 'TEHUACAN', 'Segunda ciudad mas grande de Puebla'),
(19, 'MONCLOVA', 'Ciudad industrial de acero en Coahuila'),
(19, 'REYNOSA', 'Ciudad fronteriza industrial de Tamaulipas'),
(19, 'MATAMOROS', 'Ciudad fronteriza del estado de Tamaulipas'),
(19, 'TAMPICO', 'Puerto y ciudad importante de Tamaulipas'),
(19, 'ENSENADA', 'Puerto famoso de Baja California'),
(19, 'URUAPAN', 'Ciudad de Michoacan famosa por aguacate'),
(19, 'PARIS', 'Capital francesa famosa por torre Eiffel'),
(19, 'ROMA', 'Capital de Italia famosa por coliseo'),
(19, 'LONDRES', 'Capital britanica famosa por el Big Ben'),
(19, 'TOKIO', 'Capital moderna y muy poblada Japon'),
(19, 'CHICAGO', 'Ciudad de Estados Unidos muy famosa'),
(19, 'MADRID', 'Capital de Espana famosa por museos'),
(19, 'BERLIN', 'Capital de Alemania rica en historia'),
(19, 'MOSCU', 'Capital de Rusia famosa por Kremlin'),
(19, 'PEKIN', 'Capital historica de la republica China'),
(19, 'TORONTO', 'Ciudad financiera mas grande de Canada'),
(19, 'BOGOTA', 'Capital andina del pais de Colombia'),
(19, 'LIMA', 'Capital costera y gastronomica del Peru'),
(19, 'SANTIAGO', 'Capital chilena junto a la cordillera'),
(19, 'CARACAS', 'Capital y ciudad principal de Venezuela'),
(19, 'QUITO', 'Capital ecuatoriana situada cerca del ecuador'),
(19, 'BUENOSAIRES', 'Capital de Argentina famosa por tango'),
(19, 'MIAMI', 'Ciudad costera famosa de Estados Unidos'),
(19, 'LOSANGELES', 'Ciudad famosa por cine de Hollywood'),
(19, 'LASVEGAS', 'Ciudad famosa por sus casinos iluminados'),
(19, 'NUEVAYORK', 'Ciudad estadounidense famosa por estatua libertad'),
(19, 'AMSTERDAM', 'Capital holandesa famosa por sus canales'),
(19, 'BRUSELAS', 'Capital de Belgica y sede europea'),
(19, 'VIENA', 'Capital austriaca famosa por musica clasica'),
(19, 'PRAGA', 'Capital checa famosa por sus castillos'),
(19, 'LISBOA', 'Capital costera y antigua de Portugal'),
(19, 'ATENAS', 'Capital griega cuna de la democracia'),
(19, 'ESTAMBUL', 'Ciudad turca dividida entre dos continentes'),
(19, 'ELCAIRO', 'Capital egipcia cerca de las piramides'),
(19, 'DUBAI', 'Ciudad futurista famosa por sus rascacielos'),
(19, 'SIEMREAP', 'Ciudad de Camboya famosa por templos'),
(19, 'SEUL', 'Capital moderna de Corea del Sur'),
(19, 'BANGKOK', 'Capital tailandesa famosa por sus templos'),
(19, 'SINGAPUR', 'Ciudad estado muy moderna de Asia'),
(19, 'SIDNEY', 'Ciudad australiana famosa por su opera'),
(19, 'OTTAWA', 'Capital oficial del pais de Canada'),
(19, 'WASHINGTON', 'Capital federal de los Estados Unidos'),
(19, 'HABANA', 'Capital historica del pais de Cuba'),
(19, 'MONTEVIDEO', 'Capital costera del pais de Uruguay'),
(19, 'ASUNCION', 'Capital historica del pais de Paraguay'),
(19, 'LAHABANA', 'Capital turistica del pais de Cuba'),
(19, 'BARCELONA', 'Ciudad costera muy famosa de Espana'),
(19, 'SEVILLA', 'Ciudad espanola famosa por el flamenco'),
(19, 'VENECIA', 'Ciudad italiana famosa por sus gondolas'),
(19, 'MILAN', 'Ciudad italiana famosa por la moda'),
(19, 'FLORENCIA', 'Ciudad italiana cuna del arte renacentista'),
(19, 'NIZA', 'Ciudad turistica de la costa francesa'),
(19, 'COPENHAGUE', 'Capital de Dinamarca muy famosa y limpia'),
(19, 'ESTOCOLMO', 'Capital de Suecia rodeada por agua'),
(19, 'OSLO', 'Capital de Noruega rodeada de fiordos'),
(19, 'DUBLIN', 'Capital irlandesa famosa por sus pubs');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(20, 'CORAZON', 'Organo muscular que bombea la sangre'),
(20, 'PULMON', 'Organo principal del sistema respiratorio humano'),
(20, 'CEREBRO', 'Centro de control del sistema nervioso'),
(20, 'ESTOMAGO', 'Organo donde inicia la digestion fuerte'),
(20, 'HIGADO', 'Organo grande que filtra las toxinas'),
(20, 'RIÑON', 'Organo que depura y produce orina'),
(20, 'CRANEO', 'Hueso duro que protege el cerebro'),
(20, 'FEMUR', 'Hueso mas largo del cuerpo humano'),
(20, 'COSTILLA', 'Hueso curvo que protege el torax'),
(20, 'COLUMNA', 'Estructura osea que sostiene la espalda'),
(20, 'INTESTINO', 'Tubo digestivo que absorbe los nutrientes'),
(20, 'PANCREAS', 'Organo que produce la hormona insulina'),
(20, 'TRAQUEA', 'Conducto por donde pasa el aire'),
(20, 'ARTERIA', 'Vaso sanguineo que lleva oxigeno puro'),
(20, 'VENA', 'Vaso sanguineo de retorno al corazon'),
(20, 'ESOFAGO', 'Tubo que conecta boca y estomago'),
(20, 'LENGUA', 'Organo muscular ubicado dentro la boca'),
(20, 'DIENTE', 'Estructura dura usada para la masticacion'),
(20, 'TIROIDES', 'Glandula del cuello que regula metabolismo'),
(20, 'APENDICE', 'Pequeno organo unido al intestino grueso'),
(20, 'VESICULA', 'Organo pequeno que almacena la bilis'),
(20, 'PELVIS', 'Estructura osea en la base espinal'),
(20, 'CLAVICULA', 'Hueso horizontal en el hombro superior'),
(20, 'OMOPLATO', 'Hueso plano posterior del hombro humano'),
(20, 'RODILLA', 'Articulacion principal entre muslo y pierna'),
(20, 'ROTULA', 'Hueso circular de la articulacion pierna'),
(20, 'TOBILLO', 'Articulacion entre el pie y pierna'),
(20, 'MUÑECA', 'Articulacion entre la mano y brazo'),
(20, 'CODO', 'Articulacion media del brazo humano'),
(20, 'HOMBRO', 'Articulacion superior que une el brazo'),
(20, 'CUELLO', 'Parte que conecta cabeza con tronco'),
(20, 'GARGANTA', 'Conducto interno de la zona del cuello'),
(20, 'CINTURA', 'Parte estrecha media del cuerpo humano'),
(20, 'CADERA', 'Articulacion lateral entre pelvis y pierna'),
(20, 'PANTORRILLA', 'Musculo posterior de la pierna inferior'),
(20, 'MUSLO', 'Parte superior de la pierna humana'),
(20, 'TALON', 'Parte posterior e inferior del pie'),
(20, 'OMBLIGO', 'Cicatriz central en el abdomen humano'),
(20, 'NUDILLO', 'Articulacion prominente de los dedos mano'),
(20, 'FARINGE', 'Conducto muscular detras de la boca'),
(20, 'LARINGE', 'Organo donde estan las cuerdas vocales'),
(20, 'CEREBELO', 'Parte posterior que coordina los movimientos'),
(20, 'TORAX', 'Caja osea que protege organos vitales'),
(20, 'ABDOMEN', 'Zona ventral que alberga organos digestivos'),
(20, 'PIEL', 'Organo mas grande que cubre cuerpo'),
(20, 'MEDULA', 'Tejido nervioso dentro de la columna'),
(20, 'PUPILA', 'Apertura central del ojo que capta luz'),
(20, 'RETINA', 'Tejido sensible a luz en ojo'),
(20, 'TIMPANO', 'Membrana del oido que transmite sonido'),
(20, 'ESPALDA', 'Parte posterior del tronco del cuerpo');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(21, 'ZEUS', 'Dios supremo del olimpo y del trueno'),
(21, 'POSEIDON', 'Dios griego de los mares y terremotos'),
(21, 'HADES', 'Dios del inframundo y los muertos'),
(21, 'HERA', 'Reina de los dioses y del matrimonio'),
(21, 'ATENEA', 'Diosa de la sabiduria y la guerra'),
(21, 'APOLLO', 'Dios del sol la musica y poesia'),
(21, 'ARTEMISA', 'Diosa de la caza y la luna'),
(21, 'ARES', 'Dios de la guerra y la violencia'),
(21, 'AFRODITA', 'Diosa del amor y la belleza'),
(21, 'HEFESTO', 'Dios del fuego y la metalurgia'),
(21, 'HERMES', 'Mensajero de los dioses y del comercio'),
(21, 'DIONISIO', 'Dios del vino y las celebraciones'),
(21, 'CRONOS', 'Titan del tiempo y padre de Zeus'),
(21, 'HERCULES', 'Heroe de fuerza sobrehumana e hijo Zeus'),
(21, 'PERSEO', 'Heroe legendario que derroto a Medusa'),
(21, 'TESEO', 'Heroe que vencio al voraz Minotauro'),
(21, 'AQUILES', 'Heroe invulnerable salvo por su talon'),
(21, 'MEDUSA', 'Monstruo con serpientes por cabello que petrifica'),
(21, 'MINOTAURO', 'Ser con cuerpo humano y cabeza toro'),
(21, 'CENTAURO', 'Criatura mitad hombre y mitad caballo'),
(21, 'CICLOPE', 'Gigante con un solo ojo central'),
(21, 'CERBERO', 'Perro de tres cabezas del inframundo'),
(21, 'HIDRA', 'Monstruo acuatico con multiples cabezas serpiente'),
(21, 'PEGASO', 'Caballo alado blanco de la mitologia'),
(21, 'FENIX', 'Ave fantastica que renace de cenizas'),
(21, 'SIRENA', 'Ser marino que atrae con canto'),
(21, 'GRIFO', 'Criatura mitad aguila y mitad leon'),
(21, 'QUIMERA', 'Monstruo que escupe fuego con varias partes'),
(21, 'ESFINGE', 'Monstruo con cabeza humana y cuerpo leon'),
(21, 'ARPIA', 'Ser volador con cuerpo de ave voraz'),
(21, 'ODIN', 'Dios principal de la mitologia nordica'),
(21, 'THOR', 'Dios nordico del trueno y su martillo'),
(21, 'LOKI', 'Dios nordico del engano y las trampas'),
(21, 'FREYJA', 'Diosa nordica del amor y la belleza'),
(21, 'VALQUIRIA', 'Guerrera que lleva caidos al Valhalla'),
(21, 'FENRIR', 'Lobo gigante de la mitologia nordica'),
(21, 'RA', 'Dios del sol en el Antiguo Egipto'),
(21, 'ANUBIS', 'Dios egipcio con cabeza de chacal'),
(21, 'OSIRIS', 'Dios egipcio del inframundo y la resurreccion'),
(21, 'ISIS', 'Diosa egipcia de la maternidad y magia'),
(21, 'HORUS', 'Dios egipcio con cabeza de falcon'),
(21, 'QUETZALCOATL', 'Serpiente emplumada de la mitologia azteca'),
(21, 'HUITZILOPOCHTLI', 'Dios azteca del sol y la guerra'),
(21, 'TLALOC', 'Dios azteca de la lluvia y fertilidad'),
(21, 'TEZCATLIPOCA', 'Dios azteca de la noche y magia'),
(21, 'COATLICUE', 'Diosa azteca madre de las deidades'),
(21, 'KUKULKAN', 'Dios maya equivalente a la serpiente emplumada'),
(21, 'CHAAC', 'Dios maya de la lluvia y rayos'),
(21, 'VULCANO', 'Dios romano del fuego y volcanes'),
(21, 'JUPITER', 'Dios supremo en la mitologia romana'),
(21, 'NEPTUNO', 'Dios romano de los mares profundos'),
(21, 'MARTE', 'Dios romano de la guerra y batallas'),
(21, 'VENUS', 'Diosa romana del amor y belleza'),
(21, 'MERCURIO', 'Dios romano mensajero de gran velocidad'),
(21, 'DIANA', 'Diosa romana de la caza y naturaleza'),
(21, 'MINERVA', 'Diosa romana de la sabiduria artes'),
(21, 'SATURNO', 'Dios romano de la agricultura y tiempo'),
(21, 'BACANTE', 'Sacerdotisa del dios del vino Dionisio'),
(21, 'NINFA', 'Deidad femenina menor de la naturaleza'),
(21, 'SATIRO', 'Criatura alegre con cuernos y patas cabra');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(22, 'SOFTWARE', 'Conjunto de programas e instrucciones del sistema'),
(22, 'HARDWARE', 'Componentes fisicos de una computadora'),
(22, 'INTERNET', 'Red global de computadoras interconectadas'),
(22, 'MONITOR', 'Pantalla que muestra la interfaz visual'),
(22, 'TECLADO', 'Dispositivo de entrada con teclas alfanumericas'),
(22, 'RATON', 'Dispositivo apuntador manual para computadora'),
(22, 'SERVIDOR', 'Equipo que provee servicios y recursos web'),
(22, 'ANTENA', 'Dispositivo para emitir o recibir ondas'),
(22, 'ROBOT', 'Maquina automatizada programable para tareas'),
(22, 'IMPRESORA', 'Dispositivo que pasa documentos a papel'),
(22, 'ESCANER', 'Dispositivo que digitaliza documentos e imagenes'),
(22, 'MODEM', 'Dispositivo que convierte senales de red'),
(22, 'ROUTER', 'Dispositivo que dirige el trafico de red'),
(22, 'MEMORIA', 'Componente que almacena datos temporalmente'),
(22, 'PROCESADOR', 'Unidad central que ejecuta las instrucciones'),
(22, 'PANTALLA', 'Superficie visual de un dispositivo electronico'),
(22, 'BATERIA', 'Fuente de energia recargable para portatiles'),
(22, 'CARGADOR', 'Accesorio que suministra corriente a dispositivos'),
(22, 'AUDIFONOS', 'Dispositivo de audio individual para oidos'),
(22, 'MICROFONO', 'Transductor que convierte sonido en electricidad'),
(22, 'CAMARA', 'Dispositivo que captura fotos y videos'),
(22, 'CIRCUITO', 'Red de componentes electronicos interconectados'),
(22, 'CHIP', 'Pequeno circuito integrado de silicio'),
(22, 'TARJETA', 'Placa con circuitos para funciones especificas'),
(22, 'DISCO', 'Unidad de almacenamiento magico o solido'),
(22, 'SENSOR', 'Dispositivo que detecta magnitudes fisicas'),
(22, 'CABLE', 'Conductor de electricidad o datos blindado'),
(22, 'PUERTO', 'Interfaz para conectar perifericos al equipo'),
(22, 'PIXEL', 'Unidad minima de una imagen digital'),
(22, 'SISTEMA', 'Conjunto organizado de componentes interactivos'),
(22, 'PROGRAMA', 'Secuencia de instrucciones ordenadas para ejecutar'),
(22, 'CODIGO', 'Conjunto de texto escrito en lenguaje'),
(22, 'ALGORITMO', 'Conjunto de pasos logicos para resolver'),
(22, 'VARIABLES', 'Espacio reservado en memoria para guardar'),
(22, 'MATRIZ', 'Estructura de datos en varias dimensiones'),
(22, 'ARREGLO', 'Coleccion ordenada de elementos del mismo'),
(22, 'FUNCION', 'Bloque de codigo reutilizable que realiza'),
(22, 'OBJETO', 'Instancia de una clase en programacion'),
(22, 'CLASE', 'Plantilla para crear objetos en codigo'),
(22, 'METODO', 'Accion o funcion asociada a un objeto'),
(22, 'INTERFAZ', 'Punto de interaccion entre usuario y'),
(22, 'PAGINA', 'Documento digital accesible mediante navegador web'),
(22, 'NAVEGADOR', 'Aplicacion para explorar la red de internet'),
(22, 'BUSCADOR', 'Herramienta web para encontrar informacion online'),
(22, 'CORREO', 'Servicio de mensajeria electronica digital'),
(22, 'MENSAJE', 'Texto corto enviado entre dispositivos digitales'),
(22, 'USUARIO', 'Persona que utiliza un sistema o dispositivo'),
(22, 'CLAVE', 'Secuencia secreta para autenticar la identidad'),
(22, 'TOKEN', 'Elemento de seguridad para autenticacion digital'),
(22, 'FIRMA', 'Autenticacion digital de un documento electronico'),
(22, 'RED', 'Conjunto de nodos interconectados entre si'),
(22, 'CONEXION', 'Enlace activo entre dos dispositivos informaticos'),
(22, 'DESCARGA', 'Transferencia de archivos desde un servidor'),
(22, 'SUBIDA', 'Envio de archivos hacia un servidor'),
(22, 'NUBE', 'Almacenamiento remoto accesible por red'),
(22, 'RESPALDO', 'Copia de seguridad de informacion valiosa'),
(22, 'NUCLEO', 'Parte central del sistema operativo kernel'),
(22, 'CONSOLA', 'Interfaz de linea de comandos o videojuego'),
(22, 'TERMINAL', 'Pantalla de entrada y salida de comandos'),
(22, 'COMANDO', 'Instruccion dada a un sistema informatico'),
(22, 'ARCHIVO', 'Coleccion de datos guardada con un nombre'),
(22, 'CARPETA', 'Contenedor para organizar archivos digitales'),
(22, 'FORMATO', 'Estructura especifica de un archivo digital'),
(22, 'COMPRESION', 'Reduccion del tamano de un archivo'),
(22, 'VIRUS', 'Programa malicioso que altera el sistema'),
(22, 'ANTIVIRUS', 'Software disenado para detectar malware malicioso'),
(22, 'SOPORTE', 'Servicio de asistencia tecnica para usuarios'),
(22, 'LICENCIA', 'Permiso legal para usar un software'),
(22, 'BOTON', 'Elemento de interfaz interactivo para pulsar'),
(22, 'PUNTERO', 'Indicador grafico en pantalla guiado por raton'),
(22, 'VENTANA', 'Area rectangular visual de una aplicacion'),
(22, 'ICONO', 'Representacion grafica de un programa o archivo'),
(22, 'BANNER', 'Anuncio publicitario grafico en sitio web'),
(22, 'ENLACE', 'Texto o imagen que redirige a otra'),
(22, 'ETIQUETA', 'Marca empleada para categorizar contenido digital'),
(22, 'FILTRO', 'Mecanismo que selecciona datos segun criterio'),
(22, 'MODULO', 'Parte independiente dentro de un sistema'),
(22, 'LIBRERIA', 'Coleccion de codigo reutilizable para desarrollo'),
(22, 'COMPILADOR', 'Programa que traduce codigo a lenguaje maquina'),
(22, 'EJECUTABLE', 'Archivo preparado para correr en sistema'),
(22, 'PETICION', 'Solicitud enviada a un servidor web'),
(22, 'RESPUESTA', 'Resultado devuelto por un servidor remoto'),
(22, 'PROCESO', 'Programa en ejecucion en el sistema'),
(22, 'HILO', 'Unidad minima de ejecucion en procesamiento'),
(22, 'BIT', 'Unidad minima de informacion binaria digital'),
(22, 'BYTE', 'Conjunto de ocho bits de datos'),
(22, 'KILOBYTE', 'Unidad equivalente a mil veinticuatro bytes'),
(22, 'MEGABYTE', 'Unidad de medida de memoria digital'),
(22, 'GIGABYTE', 'Unidad de almacenamiento equivalente a mil megas'),
(22, 'TERABYTE', 'Gran capacidad de almacenamiento de datos');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(23, 'GALAXIA', 'Vasta acumulacion de estrellas gas y polvo'),
(23, 'ESTRELLA', 'Esfera masiva de plasma que emite luz'),
(23, 'PLANETA', 'Cuerpo celeste que orbita alrededor de una'),
(23, 'COMETA', 'Cuerpo helado que despliega una cola brillante'),
(23, 'METEORO', 'Haz luminoso producido por un meteoroide terrestre'),
(23, 'ASTEROIDE', 'Cuerpo rocoso que orbita en el sistema'),
(23, 'SATURNO', 'Planeta famoso por su sistema de anillos'),
(23, 'JUPITER', 'El planeta mas grande del sistema solar'),
(23, 'MARTE', 'El conocido como planeta rojo del sistema'),
(23, 'VENUS', 'Planeta mas brillante visto desde la Tierra'),
(23, 'MERCURIO', 'Planeta mas cercano a la estrella solar'),
(23, 'NEPTUNO', 'Planeta gigante helado de color azul intenso'),
(23, 'URANO', 'Planeta gigante helado con rotacion muy inclinada'),
(23, 'PLUTON', 'Famoso planeta enano del sistema solar lejano'),
(23, 'SOL', 'Estrella central de nuestro sistema planetario'),
(23, 'LUNA', 'Satelite natural que orbita la Tierra'),
(23, 'ECLIPSE', 'Ocultacion temporal de un cuerpo celeste por'),
(23, 'ORBITA', 'Trayectoria curva de un cuerpo alrededor de'),
(23, 'CRATER', 'Depresion circular causada por el impacto de'),
(23, 'NEBULOSA', 'Nube gigante de polvo y gas en'),
(23, 'SUPERNOVA', 'Explosion masiva y brillante de una estrella'),
(23, 'PULSAR', 'Estrella de neutrones que emite radiacion periodica'),
(23, 'QUASAR', 'Fuente de energia extremadamente brillante y lejana'),
(23, 'COSMOS', 'El universo conjunto de todo lo existente'),
(23, 'UNIVERSO', 'Totalidad del espacio tiempo materia y energia'),
(23, 'GRAVEDAD', 'Fuerza de atraccion entre los cuerpos masivos'),
(23, 'CONSTELACION', 'Agrupacion de estrellas que forma una figura'),
(23, 'ORION', 'Constelacion famosa visible en ambos hemisferios'),
(23, 'ANDROMEDA', 'Galaxia espiral mas cercana a la nuestra'),
(23, 'TELESCOPIO', 'Instrumento optico para observar astros lejanos'),
(23, 'OBSERVATORIO', 'Lugar equipado para el estudio del espacio'),
(23, 'ASTRONAUTA', 'Persona entrenada para viajar al espacio exterior'),
(23, 'COHETE', 'Vehiculo proyectil impulsado para viajes espaciales'),
(23, 'SATELITE', 'Objeto natural o artificial que orbita un'),
(23, 'MODULO', 'Nave o seccion de un viaje espacial'),
(23, 'SONDA', 'Nave no tripulada enviada al espacio'),
(23, 'GEMINIS', 'Constelacion famosa del zodiaco espacial'),
(23, 'TAURO', 'Constelacion destacada de la franja zodiacal'),
(23, 'LEO', 'Constelacion que representa a un leon celestial'),
(23, 'AURORA', 'Fenomeno luminoso provocado por radiacion solar'),
(23, 'MAGNITUD', 'Medida del brillo aparente de una estrella'),
(23, 'CUMULO', 'Agrupacion densa de miles de estrellas unidas'),
(23, 'POLVO', 'Materia fina dispersa en el espacio intergalactico'),
(23, 'ZENIT', 'Punto mas alto del cielo sobre un'),
(23, 'NADIR', 'Punto opuesto al zenit en la esfera'),
(23, 'SOLSTICIO', 'Momento del ano de mayor o menor'),
(23, 'EQUINOCCIO', 'Momento en que el dia y la'),
(23, 'ZODIACO', 'Banda de la esfera celeste dividida en'),
(23, 'EXOPLANETA', 'Planeta que orbita una estrella fuera del'),
(23, 'NEUTRON', 'Particula que compone cierto tipo de estrellas'),
(23, 'TITAN', 'Luna mas grande del planeta Saturno'),
(23, 'EUROPA', 'Luna helada del gigante planeta Jupiter'),
(23, 'GANIMEDES', 'La luna mas grande de todo el'),
(23, 'CALISTO', 'Luna muy craterizada del planeta Jupiter'),
(23, 'IO', 'Luna volcanica activa del planeta Jupiter'),
(23, 'ATMOSFERA', 'Capa de gases que rodea a un'),
(23, 'CORONA', 'Capa mas externa de la atmosfera solar'),
(23, 'MANCHA', 'Region con menor temperatura en el sol'),
(23, 'ASTRONOMIA', 'Ciencia que estudia los cuerpos celestes universo'),
(23, 'COSMONAUTA', 'Astronauta de la escuela espacial rusa');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(24, 'VOLCAN', 'Estructura geologica que expulsa magma y ceniza'),
(24, 'DESIERTO', 'Bioma seco con muy escasa precipitacion'),
(24, 'CASCADA', 'Caida vertical de agua en un rio'),
(24, 'GLACIAR', 'Masa de hielo acumulada en las montanas'),
(24, 'ARRECIFE', 'Estructura marina formada por colonias de coral'),
(24, 'PENINSULA', 'Extension de tierra rodeada de agua casi totalmente'),
(24, 'LAGUNA', 'Deposito natural de agua generalmente mas pequeno'),
(24, 'CAÑON', 'Paso estrecho entre montanas esculpido por rios'),
(24, 'ARCHIPIELAGO', 'Conjunto o grupo de islas en el mar'),
(24, 'ESTRECHO', 'Paso angosto de agua entre dos tierras'),
(24, 'MESETA', 'Planicie elevada sobre el nivel del mar'),
(24, 'CORDILLERA', 'Cadena montana de gran extension de picos'),
(24, 'CUEVA', 'Cavidad subterranea natural formada en las rocas'),
(24, 'PANTANO', 'Terreno bajo y humedo cubierto de agua'),
(24, 'SELVA', 'Bosque denso y tropical con gran biodiversidad'),
(24, 'BOSQUE', 'Ecosistema con alta densidad de arboles y vegetacion'),
(24, 'PRADERA', 'Ecosistema plano cubierto principalmente de pastos verdes'),
(24, 'SAVANA', 'Llanura con pastos altos y arboles dispersos'),
(24, 'SABANA', 'Llanura de clima tropical con arboles dispersos'),
(24, 'VALLE', 'Llanura ubicada entre colinas o elevadas montanas'),
(24, 'GOLFO', 'Gran porcion de mar que entra en la tierra'),
(24, 'BAHIA', 'Entrada de mar mas pequena que un golfo'),
(24, 'ISLA', 'Masa de tierra rodeada totalmente por agua'),
(24, 'ACANTILADO', 'Corte vertical en la roca junto al mar'),
(24, 'GEYSER', 'Fuente termal que emite chorros de agua caliente'),
(24, 'CENOTE', 'Pozo de agua dulce en depresiones calizas'),
(24, 'MANANTIAL', 'Nacimiento natural de agua desde el suelo'),
(24, 'TUNDRA', 'Bioma de clima extremadamente frio y sin arboles'),
(24, 'ATOLON', 'Isla coralina en forma de anillo con laguna'),
(24, 'SISMOS', 'Movimiento brusco de la corteza terrestre por tectonica'),
(24, 'TERREMOTO', 'Temblor fuerte de la tierra por placas tectonicas'),
(24, 'MAREMOTO', 'Ola gigante generada por un sismo marino'),
(24, 'HURACAN', 'Ciclon tropical con vientos de alta velocidad'),
(24, 'TORNADO', 'Embudos de aire que giran violentamente tocando suelo'),
(24, 'NEBLINA', 'Nube baja que dificulta la vision horizontal'),
(24, 'GRANIZO', 'Precipitacion de hielo en forma de bolas'),
(24, 'NUBE', 'Masa visible formada por cristales o gotas agua'),
(24, 'OASIS', 'Zona con agua y vegetacion en el desierto'),
(24, 'DELTA', 'Desembocadura de un rio dividida en varios brazos'),
(24, 'FOSA', 'Depresion profunda en el fondo del oceano'),
(24, 'ALUD', 'Masa grande de nieve que se desliza colina abajo'),
(24, 'CRATER', 'Depresion redonda en la cima de un volcan'),
(24, 'COLINA', 'Elevacion natural de terreno menor que una montana'),
(24, 'CERRO', 'Elevacion aislada de tierra de menor altura'),
(24, 'CUMBRE', 'Punto mas alto de una montana o pico'),
(24, 'PICO', 'Cima puntiaguda de una gran montana rocosa'),
(24, 'RIO', 'Corriente natural de agua que fluye al mar'),
(24, 'ARROYO', 'Caudal corto de agua de escaso volumen continuo'),
(24, 'OCEANO', 'Gran masa de agua salada que cubre la tierra'),
(24, 'MAREA', 'Cambio periodico del nivel del agua del mar'),
(24, 'ESTUARIO', 'Desembocadura de un rio amplio en el mar'),
(24, 'LAGO', 'Gran masa de agua dulce rodeada de tierra'),
(24, 'PLAYA', 'Ribera plana de arena o piedras junto al agua'),
(24, 'DUNAS', 'Monticulo de arena formado por accion del viento'),
(24, 'MAGMA', 'Roca fundida localizada en el interior de la tierra'),
(24, 'LAVA', 'Magma expulsado por un volcan sobre la superficie'),
(24, 'PIEDRA', 'Materia mineral dura y solida de la tierra'),
(24, 'CORAL', 'Organismo marino que forma coloridos arrecifes rocosos'),
(24, 'MUSGO', 'Planta muy pequena que crece en zonas humedas'),
(24, 'MANGLE', 'Arbol adaptable que crece en zonas de manglares'),
(24, 'ALGA', 'Organismo fotosintetico primario que vive en el agua'),
(24, 'ESPINA', 'Estructura punzante de algunas plantas o vegetacion'),
(24, 'HOJA', 'Organo verde de las plantas que fotosintetiza'),
(24, 'RAIZ', 'Parte subterranea de una planta que fija y nutre'),
(24, 'TRONCO', 'Tallo lenoso y fuerte de los grandes arboles'),
(24, 'RAMA', 'Parte que nace del tronco de un arbol'),
(24, 'SEMILLA', 'Estructura reproductiva que da origen a una planta'),
(24, 'BROTE', 'Renuevo que empieza a salir en una planta'),
(24, 'FLORA', 'Conjunto de plantas caracteristicas de una region'),
(24, 'FAUNA', 'Conjunto de animales de una region o ecosistema');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(25, 'GARFIELD', 'Gato naranja famoso que adora la lasana'),
(25, 'CENICIENTA', 'Princesa que pierde una zapatilla de cristal'),
(25, 'MICKEY', 'Raton famoso emblema de la compania Disney'),
(25, 'PINOCHO', 'Muneco de madera al que le crece nariz'),
(25, 'SHREK', 'Ogro verde que vive en un pantano'),
(25, 'BLANCANIEVES', 'Princesa que vive con siete enanos atentos'),
(25, 'BOBESPONJA', 'Esponja amarilla que vive bajo el mar'),
(25, 'TARZAN', 'Hombre criado por simios en la selva'),
(25, 'ALADDIN', 'Joven que encuentra una lampara con genio'),
(25, 'MULAN', 'Valiente joven que lucha por su familia'),
(25, 'SIMBA', 'Cachorro de leon destinado a ser rey'),
(25, 'BAMBI', 'Pequeno ciervo famoso de la pelicula animada'),
(25, 'DUMBO', 'Pequeno elefante famoso por sus grandes orejas'),
(25, 'POPEYE', 'Marinero fuerte que obtiene poder comiendo espinacas'),
(25, 'SNOOPY', 'Perro blanco muy famoso de tira comica'),
(25, 'BATMAN', 'Heroe nocturno que protege la ciudad Gotica'),
(25, 'SUPERMAN', 'Heroe alienigena con superfuerza y capa roja'),
(25, 'SPIDERMAN', 'Heroe que trepa paredes vistiendo traje rojo'),
(25, 'POKEMON', 'Criatura fantastica entrenada para combatir en duelos'),
(25, 'PIKACHU', 'Criatura electrica amarilla companero de Ash Ketchum'),
(25, 'CHARIZARD', 'Dragon de fuego famoso de la saga Pokemon'),
(25, 'SONIC', 'Erizos azul de gran velocidad en videojuegos'),
(25, 'MARIO', 'Fontanero italiano que rescata a la princesa'),
(25, 'LUIGI', 'Hermano del fontanero Mario de traje verde'),
(25, 'YOSHI', 'Dinosaurio verde amigo del fontanero Mario Bros'),
(25, 'BOWSER', 'Villano tortuga enemigo del fontanero Mario Bros'),
(25, 'KIRBY', 'Personaje rosado redondo que absorbe sus enemigos'),
(25, 'MINION', 'Pequeno ser amarillo que sirve a Gru'),
(25, 'OLAF', 'Muneco de nieve simpatico de la pelicula Frozen'),
(25, 'ELSA', 'Princesa con poderes de hielo y nieve'),
(25, 'ANNA', 'Hermana menor de la reina del hielo Elsa'),
(25, 'MOANA', 'Joven navegante que cruza el océano pacifico'),
(25, 'RAPUNZEL', 'Princesa de cabellera rubia extremadamente larga y dorada'),
(25, 'HERMIONE', 'Joven maga muy inteligente amiga de Harry'),
(25, 'HARRY', 'Joven mago famoso con cicatriz de rayo'),
(25, 'RON', 'Mago de cabello pelirrojo amigo de Harry'),
(25, 'VOLDEMORT', 'Villano mago tenebroso enemigo de Harry Potter'),
(25, 'PETERPAN', 'Nino que nunca crece y puede volar'),
(25, 'TITAN', 'Heroe gigante animado de la television infantil'),
(25, 'DORA', 'Nina exploradora que viaja con un mono'),
(25, 'PLUTO', 'Perro amarillo mascota del raton Mickey Mouse'),
(25, 'GOOFY', 'Amigo alto y torpe del raton Mickey'),
(25, 'DONALD', 'Pato famoso temperamental de traje marinero azul'),
(25, 'DAISY', 'Pata elegante novia del famoso pato Donald'),
(25, 'MINNIE', 'Ratona famosa novia del conocido Mickey Mouse'),
(25, 'TINKERBELL', 'Pequena hada verde companera de Peter Pan'),
(25, 'BAMBAM', 'Bebe fuerte de la familia de Picapiedra'),
(25, 'NEPTUNO', 'Rey del mar en historias marinas infantiles'),
(25, 'NEMO', 'Pez payaso que se pierde en oceano'),
(25, 'DORY', 'Pez azul olvidadizo amiga del pez Nemo'),
(25, 'BUZZ', 'Guardian espacial de juguete amigo de Woody'),
(25, 'WOODY', 'Vaquero de juguete lider en Toy Story'),
(25, 'FORKY', 'Tenedor juguete hecho a mano por Bonnie'),
(25, 'SULLIVAN', 'Monstruo azul peludo amigo de Mike Wazowski'),
(25, 'WAZOWSKI', 'Monstruo verde de un solo ojo grande'),
(25, 'MACQUEEN', 'Auto de carreras rojo protagonista de Cars'),
(25, 'MATE', 'Grua oxidada amigable companera del Rayo McQueen'),
(25, 'REMY', 'Rata talentosa que suena con ser chef'),
(25, 'WALLE', 'Pequeno robot basurero que limpia la Tierra'),
(25, 'EVA', 'Robot moderna blanca que busca vida vegetal'),
(25, 'MASHA', 'Niña pequeña que vive con oso'),
(25, 'OSO', 'Oso grande que cuida vive con niña'),
(25, 'MADAGASCAR', 'Cebra que sueña con la vida salvaje'),
(25, 'ALEX', 'Leon famoso estrella del zoologico de Nueva York'),
(25, 'MELMAN', 'Jirafa miedosa y enfermiza del zoologico urbano'),
(25, 'GLORIA', 'Hipopotamo femenina fuerte del grupo de Madagascar'),
(25, 'STITCH', 'Experimento alienigena azul adoptado como perro en Hawaii'),
(25, 'LILO', 'Nina hawaiana que adopta al alienigena Stitch'),
(25, 'MEGAMIND', 'Villano azul de gran cabeza que se vuelve bueno'),
(25, 'METROMAN', 'Heroe perfecto rival del villano Megamente en ciudad'),
(25, 'CASPER', 'Fantasma amigable que no asusta a humanos'),
(25, 'PADDINGTON', 'Oso tierno que viaja desde el Peru'),
(25, 'CLIFFORD', 'Gran perro rojo gigante amigo de Emily'),
(25, 'CAILLOU', 'Nino pequeno curioso que aprende del mundo diario'),
(25, 'POCOYO', 'Nino vestido de azul que descubre las cosas'),
(25, 'PEPPA', 'Cerdita rosada famosa que vive con su familia'),
(25, 'GEORGE', 'Hermano menor de la cerdita Peppa Pig'),
(25, 'BOBBY', 'Pequeno perro animado de aventuras infantiles cotidianas'),
(25, 'TOTO', 'Pequeno perro companero de Dorothy en Oz');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(26, 'RASCACIELOS', 'Edificio de gran altura y muchas plantas'),
(26, 'CATEDRAL', 'Iglesia principal donde reside el obispo diocesano'),
(26, 'PIRAMIDE', 'Construccion monumental antigua con base poligonal'),
(26, 'CASTILLO', 'Edificacion fortificada propia de la epoca medieval'),
(26, 'MONASTERIO', 'Convento donde vive una comunidad de monjes'),
(26, 'PALACIO', 'Residencia lujosa de reyes o grandes dignatarios'),
(26, 'TEMPLO', 'Edificio sagrado destinado al culto religioso diverso'),
(26, 'BASILICA', 'Iglesia notable por su valor historico o liturgico'),
(26, 'CAPILLA', 'Lugar de culto pequeno integrado en edificio'),
(26, 'SANTUARIO', 'Templo donde se venera una imagen sagrada'),
(26, 'PAGODA', 'Edificio religioso de varios pisos en Asia'),
(26, 'MEZQUITA', 'Lugar de culto para los fieles musulmanes'),
(26, 'SINAGOGA', 'Lugar de reunion y culto del judaismo'),
(26, 'IGLESIA', 'Edificio cristiano destinado al culto y oracion'),
(26, 'CONVENTO', 'Edificio donde residen comunidades religiosas o monjas'),
(26, 'FORTALEZA', 'Edificacion militar defensiva reforzada contra ataques'),
(26, 'ALCAZAR', 'Recinto fortificado o palacio de origen arabe'),
(26, 'TORRE', 'Edificacion mas alta que ancha aislada o unida'),
(26, 'FARO', 'Torre costera con luz para guiar barcos'),
(26, 'MURALLA', 'Muro defensivo que rodea una ciudad antigua'),
(26, 'COLISEO', 'Gran anfiteatro romano usado para espectaculos publicos'),
(26, 'ESTADIO', 'Instalacion deportiva grande con gradas para espectadores'),
(26, 'ARENA', 'Recinto cerrado para eventos deportivos o conciertos'),
(26, 'TEATRO', 'Edificio destinado a la representacion de obras'),
(26, 'AUDITORIO', 'Recinto disenado para conciertos y conferencias masivas'),
(26, 'MUSEO', 'Lugar donde se conservan y exhiben obras'),
(26, 'BIBLIOTECA', 'Edificio que alberga colecciones de libros organizados'),
(26, 'HOSPITAL', 'Edificio equipado para la atencion medica continua'),
(26, 'CLINICA', 'Centro medico privado o especializado de salud'),
(26, 'HOTEL', 'Edificio para alojamiento temporal de viajeros turistas'),
(26, 'HOSTAL', 'Alojamiento economico con servicios e instalaciones comunes'),
(26, 'MOTEL', 'Hotel de carretera pensado para estancias cortas'),
(26, 'RESIDENCIA', 'Edificio destinado a la vivienda permanente o estudiantil'),
(26, 'EMBAJADA', 'Oficina diplomatica de un pais en el extranjero'),
(26, 'CONSULADO', 'Oficina diplomatica que atiende a sus ciudadanos'),
(26, 'CAPITOLIO', 'Edificio donde se reune el cuerpo legislativo'),
(26, 'PALACETE', 'Palacio de dimensiones reducidas pero estilo elegante'),
(26, 'MANSION', 'Casa urbana o rural de grandes dimensiones lujosa'),
(26, 'HACIENDA', 'Finca agricola o ganadera con gran casona'),
(26, 'CASONA', 'Casa grande antigua de arquitectura tradicional o elegante'),
(26, 'RANCHERIA', 'Conjunto de viviendas rurales dispersas o sencillas'),
(26, 'MERCADO', 'Edificio donde se comercializan alimentos y productos'),
(26, 'BAZAR', 'Mercado cubierto tradicional con puestos de venta'),
(26, 'CENTRO', 'Edificio comercial de gran tamano con tiendas'),
(26, 'ALMACEN', 'Edificio destinado al deposito y guardado mercancías'),
(26, 'BODEGA', 'Lugar destinado a guardar vino u otros productos'),
(26, 'FABRICA', 'Edificio industrial donde se transforman materias primas'),
(26, 'PLANTA', 'Instalacion industrial de procesamiento o energia electrica'),
(26, 'REFINERIA', 'Planta industrial donde se procesa el petroleo'),
(26, 'ESTACION', 'Edificio de transportes para pasajeros de trenes'),
(26, 'AEROPUERTO', 'Instalacion para el despegue y aterrizaje aviones'),
(26, 'PUERTO', 'Instalacion costera para el atracadero de barcos'),
(26, 'HANGAR', 'Gran cubierta donde se guardan aeronaves o aviones'),
(26, 'PUENTE', 'Estructura construida para cruzar rios o abismos'),
(26, 'ACUEDUCTO', 'Construccion que transporta agua a largas distancias'),
(26, 'VIADUCTO', 'Puente largo sobre un valle o zona baja'),
(26, 'TUNEL', 'Paso subterraneo abierto a traves de una montana'),
(26, 'PRESA', 'Barrera construida para contener el agua de rios'),
(26, 'DIQUE', 'Muro de contencion para evitar inundaciones marinas'),
(26, 'OBSERVATORIO', 'Edificio con cupula para observar el firmamento'),
(26, 'PLANETARIO', 'Edificio equipado para proyecciones astronomicas educativas'),
(26, 'INVERNADERO', 'Recinto acristalado para el cultivo de plantas'),
(26, 'PENITENCIARIA', 'Edificio o carcel de maxima seguridad estatal'),
(26, 'CARCEL', 'Edificio destinado a la reclusion de prisioneros'),
(26, 'CUARTEL', 'Edificio militar donde se alojan las tropas'),
(26, 'ALBERGUE', 'Edificio de acogida o alojamiento de paso'),
(26, 'KIOSKO', 'Construccion ligera ubicada en plazas o parques'),
(26, 'GAZEBO', 'Estructura ligera de jardin abierta por lados'),
(26, 'PERGOLA', 'Estructura de jardin cubierta de plantas trepadoras'),
(26, 'MAUSOLEO', 'Monumento funerario levantado sobre una tumba');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(27, 'PELOTA', 'Objeto esferico usado para rebotar y jugar'),
(27, 'MUÑECA', 'Juguete con forma humana para jugar a cuidar'),
(27, 'CANICAS', 'Pequenas esferas de vidrio para jugar en suelo'),
(27, 'PATINETA', 'Tabla con ruedas usada para deslizarse y piruetas'),
(27, 'CARRITO', 'Vehiculo de juguete pequeno a escala para ninos'),
(27, 'BLOQUES', 'Piezas de plastico o madera para construir torres'),
(27, 'TROMPO', 'Juguete de madera que gira sobre su punta'),
(27, 'YOYO', 'Disco que sube y baja por un cordon'),
(27, 'PINATA', 'Figura de carton llena de dulces para romper'),
(27, 'BALON', 'Pelota grande usada para deportes y juegos colectivos'),
(27, 'PATINES', 'Calzado con ruedas inferiores para deslizarse en pista'),
(27, 'TRICICLO', 'Vehiculo de tres ruedas pedaleado por ninos pequenos'),
(27, 'BICICLETA', 'Vehiculo de dos ruedas impulsado mediante pedales manuales'),
(27, 'AVIONCITO', 'Juguete clasico de papel o plastico volador'),
(27, 'SERPIENTES', 'Juego de mesa clasico con dados y escaleras'),
(27, 'DOMINO', 'Juego de fichas rectangulares con puntos marcados'),
(27, 'AJEDREZ', 'Juego de estrategia en tablero con reyes torres'),
(27, 'LOTERIA', 'Juego tradicional mexicano con cartas e imagenes variadas'),
(27, 'MEMORAMA', 'Juego de cartas para buscar parejas iguales ocultas'),
(27, 'BINGO', 'Juego de azar con esferas numeradas y tarjetas'),
(27, 'DADOS', 'Cubos numerados usados para avanzar en juegos mesa'),
(27, 'CUBORUBIK', 'Rompecabezas cubico de colores para alinear caras'),
(27, 'SLIME', 'Masa pegajosa y moldeable de colores llamativos jugables'),
(27, 'PLASTILINA', 'Masa suave de colores usada para moldear figuras'),
(27, 'CRAYONES', 'Barras de cera de colores para dibujar papel'),
(27, 'ACUARELAS', 'Pinturas secas que se activan con agua dulce'),
(27, 'PINCEL', 'Herramienta con cerdas usada para pintar dibujos infantiles'),
(27, 'BURBUJERO', 'Juguete para soplar y crear esferas de jabon'),
(27, 'MATATENA', 'Juego tradicional con piezas metalicas y pelota chica'),
(27, 'BALERO', 'Juguete de madera con mango e hilo atado'),
(27, 'COMETA', 'Armazon de papel que vuela con el viento'),
(27, 'PUPPET', 'Titere de mano usado para obras teatrales infantiles'),
(27, 'TITERE', 'Figura articulada movida por hilos o por mano'),
(27, 'MARIONETA', 'Figura de madera movida por hilos desde arriba'),
(27, 'FUTBOLITO', 'Mesa con barras y munecos para jugar futbol'),
(27, 'CARRUSEL', 'Atraccion giratoria con figuras de caballos para montar'),
(27, 'RESBALADILLA', 'Rampa inclinada para deslizarse en parques infantiles'),
(27, 'COLUMPIO', 'Asiento colgado de cadenas para mecerse en aire'),
(27, 'SUBEBAJA', 'Asiento largo balancin de dos lugares para ninos'),
(27, 'CASITA', 'Estructura pequena de juguete para jugar adentro'),
(27, 'PELUCHE', 'Muneco suave rellenado de algodon con forma animal'),
(27, 'OSO', 'Peluche clasico con forma de animal abrazable suave'),
(27, 'DINOSAURIO', 'Figura de plastico de reptil extinto de juguete'),
(27, 'ROBOT', 'Juguete mecanico o electronico con luces y sonidos'),
(27, 'CAMION', 'Vehiculo pesado de juguete para transportar tierra o arena'),
(27, 'TREN', 'Locomotora de juguete que rueda sobre rieles armables'),
(27, 'TRENECITO', 'Vehiculo infantil de madera o plastico sobre vias'),
(27, 'PISTOLA', 'Juguete que dispara agua o dardos de espuma'),
(27, 'ESPADA', 'Arma de juguete hecha de plastico o espuma'),
(27, 'ESCUDO', 'Proteccion de juguete usada por caballeros o superheroes'),
(27, 'DISFRAZ', 'Ropa especial para caracterizarse como personaje o superheroe'),
(27, 'MASCARA', 'Accesorio para cubrir el rostro en juegos infantiles'),
(27, 'VARITA', 'Objeto magico de juguete para hacer trucos fantasticos'),
(27, 'TAMBOR', 'Instrumento de juguete para golpear y hacer ritmo'),
(27, 'XILOFONO', 'Instrumento infantil con laminas de colores de metal'),
(27, 'FLAUTA', 'Instrumento dulce de plastico para soplar notas simples'),
(27, 'SONAJA', 'Juguete para bebes que emite sonido al agitarse'),
(27, 'MORDEDERA', 'Objeto suave de silicon para aliviar encias bebes'),
(27, 'GIMNASIO', 'Manta con juguetes colgantes para bebes acostados'),
(27, 'ALBERCA', 'Piscina inflable llena de pelotas de plastico livianas');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(1, 'TAMAL', 'Masa de maíz rellena cocida al vapor en hoja'),
(1, 'ENCHILADA', 'Tortilla de maíz bañada en salsa picante y rellena'),
(1, 'POZOLE', 'Caldo tradicional a base de granos de maíz y carne'),
(1, 'QUESADILLA', 'Tortilla doblada a la mitad rellena de queso fundido'),
(1, 'MOLE', 'Salsa tradicional mexicana elaborada con chiles y especias'),
(1, 'TORTA', 'Pan bolillo rellenado con diversos ingredientes calientes'),
(1, 'SOPES', 'Base gruesa de maíz con pellizco de guisado'),
(1, 'CHILAQUILES', 'Totopos de maíz bañados en salsa verde o roja'),
(1, 'GORDITA', 'Masa gruesa de maíz rellena de chicharrón o queso'),
(1, 'TOSTADA', 'Tortilla de maíz frita o horneada muy crujiente'),
(1, 'EMPANADA', 'Masa de trigo o maíz rellena horneada o frita'),
(1, 'FLAUTA', 'Taco enrollado de tortilla de maíz muy frito'),
(1, 'GUACAMOLE', 'Salsa de aguacate machacado con cebolla y cilantro'),
(1, 'CARNITAS', 'Carne de cerdo cocida lentamente en su propia grasa'),
(1, 'BARBACOA', 'Carne de borrego cocida tradicionalmente en pozo'),
(1, 'CHICHARRON', 'Piel de cerdo frita de textura muy crujiente'),
(1, 'CHALUPA', 'Pequeña tortilla frita servida con salsa y carne'),
(1, 'TLACOYO', 'Masa ovalada de maíz rellena de frijol o haba'),
(1, 'NOPAL', 'Cactus comestible de sabor fresco muy tradicional'),
(1, 'ELOTE', 'Mazorca de maíz tierno servida con crema y queso'),
(1, 'ESQUITES', 'Granos de maíz hervidos servidos en vaso con mayonesa'),
(1, 'HUARACHE', 'Masa alargada de maíz con frijoles y guisados arriba'),
(1, 'MEMELA', 'Tortilla ovalada y gruesa típica del estado de Oaxaca'),
(1, 'PASTOR', 'Carne de cerdo marinada cocida en trompo vertical'),
(1, 'SUADERO', 'Corte suave de carne de res muy popular en tacos'),
(1, 'ALAMBRE', 'Guisado con carne salteada, pimientos, cebolla y queso'),
(1, 'CEVICHE', 'Pescado o marisco curado en jugo de limón fresco'),
(1, 'AGUACHILE', 'Camarones crudos marinados en picante verde de limón'),
(1, 'PULPO', 'Molusco marino de tentáculos cocinado de varias formas'),
(1, 'LANGOSTA', 'Crustáceo marino de carne fina considerada de lujo'),
(1, 'JAIBA', 'Cangrejo de agua salada de sabor suave y dulce'),
(1, 'OSTION', 'Molusco marino consumido fresco en su propia concha'),
(1, 'MOJARRA', 'Pescado entero frito muy consumido en las playas'),
(1, 'ALMENDRA', 'Fruto seco crujiente de forma alargada y nutritivo'),
(1, 'NUEZ', 'Fruto seco con cáscara dura muy rico en grasas'),
(1, 'CACAHUATE', 'Legumbre de cáscara quebradiza muy consumida como botana'),
(1, 'PISTACHE', 'Fruto seco de color verde claro y cáscara abierta'),
(1, 'AVELLANA', 'Fruto seco redondo muy usado en cremas de dulce'),
(1, 'PIÑON', 'Semilla comestible pequeña extraída de las piñas de pino'),
(1, 'AJONJOLI', 'Semillas pequeñas usadas para decorar pan o salsa mole'),
(1, 'CHIA', 'Semillas pequeñas ricas en fibra que absorben agua'),
(1, 'ARANDANO', 'Fruto rojo pequeño de sabor entre dulce y ácido'),
(1, 'FRAMBUESA', 'Fruta pequeña y roja formada por pequeñas drupas'),
(1, 'ZARZAMORA', 'Fruto silvestre oscuro de sabor dulce y ligeramente ácido'),
(1, 'HIGO', 'Fruta dulce de piel fina y muchas semillas interiores'),
(1, 'CIRUELA', 'Fruta jugosa de piel morada o amarilla con hueso'),
(1, 'DAMASCO', 'Fruta pequeña de color anaranjado parecida al durazno'),
(1, 'GRANADA', 'Fruta dura que contiene granos rojos muy jugosos'),
(1, 'TEJOCOTE', 'Fruto anaranjado típico de las fiestas navideñas y ponche'),
(1, 'CAPULIN', 'Fruto pequeño de color negro brillante parecido a la cereza'),
(1, 'ZAPOTE', 'Fruta tropical de pulpa suave de color negro o mamey'),
(1, 'MAMEY', 'Fruta tropical de cáscara marrón y pulpa anaranjada dulce'),
(1, 'JICAMA', 'Raíz fresca y crujiente muy consumida con limón'),
(1, 'BETABEL', 'Raíz dulce de color morado intenso que tiñe'),
(1, 'RABANO', 'Raíz picante de piel roja e interior muy blanco'),
(1, 'CALABAZA', 'Verdura de cáscara dura consumida en guisados y dulces'),
(1, 'CALABACITA', 'Verdura tierna de color verde muy común en la cocina'),
(1, 'EJOTE', 'Vaina verde de la planta de frijol consumida tierna'),
(1, 'ACELGA', 'Hoja verde grande con penca gruesa de uso culinario'),
(1, 'ALCACHOFA', 'Flor comestible de hojas verdes y corazón muy tierno'),
(1, 'APIO', 'Tallo verde crujiente de sabor muy fresco y aromático'),
(1, 'BERENJENA', 'Verdura de piel morada brillante y pulpa muy esponjosa'),
(1, 'CHAYOTE', 'Verdura verde con espinas de sabor suave y fresco'),
(1, 'ALBAHACA', 'Planta aromática fresca usada para cocinar pesto o pasta'),
(1, 'CILANTRO', 'Hierba verde picada indispensable en los tacos mexicanos'),
(1, 'PEREJIL', 'Hierba verde rizada de sabor fresco usada en caldos'),
(1, 'EPAZOTE', 'Hierba aromática de olor fuerte usada para los frijoles'),
(1, 'OREGANO', 'Especia seca muy aromática usada en el pozole fresco'),
(1, 'PIMIENTA', 'Condimento pequeño en grano que aporta picor y sabor'),
(1, 'CANELA', 'Corteza aromática de árbol usada en postres y bebidas'),
(1, 'VAINILLA', 'Aroma dulce obtenido de las vainas de una orquídea'),
(1, 'CLAVO', 'Especia seca de sabor muy intenso usada en guisados'),
(1, 'COMINO', 'Especia de olor fuerte muy usada en guisados mexicanos'),
(1, 'AZAFRAN', 'Especia de gran valor que da color amarillo a paellas'),
(1, 'MOSTAZA', 'Salsa condimento de color amarillo picante e intenso'),
(1, 'MAYONESA', 'Salsa cremosa hecha a base de huevo y aceite frito'),
(1, 'CATSUP', 'Salsa dulce a base de tomate para papas fritas'),
(1, 'CROQUETA', 'Porción de masa frita empanizada rellena de pollo o carne'),
(1, 'CHURRO', 'Masa frita de harina espolvoreada con azúcar y canela'),
(1, 'DONA', 'Pan dulce esponjoso en forma de rosca glaseada'),
(1, 'BUÑUELO', 'Masa de harina frita muy crujiente espolvoreada con azúcar'),
(1, 'FLAN', 'Postre cremoso a base de huevo con salsa de caramelo'),
(1, 'GELATINA', 'Postre cuajado transparente de sabores frutales y fresco'),
(1, 'NATA', 'Capa cremosa que se forma sobre la leche hervida'),
(1, 'JAMON', 'Embutido elaborado de la pierna de cerdo curada'),
(1, 'SALCHICHA', 'Embutido picado largo de carne consumido en hot dogs'),
(1, 'TOCINO', 'Tira de grasa de cerdo curada muy crujiente al freír'),
(1, 'CHORIZO', 'Embutido condimentado de color rojo muy usado en tacos'),
(1, 'LONGANIZA', 'Embutido largo de carne de cerdo adobada y condimentada'),
(1, 'SALAMI', 'Embutido curado de sabor fuerte picado finamente');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(2, 'HIPOPOTAMO', 'Gran mamífero semiacuático de mandíbulas muy fuertes'),
(2, 'RINOCERONTE', 'Mamífero grande con uno o dos cuernos en su hocico'),
(2, 'GUEPARDO', 'El mamífero terrestre más rápido de todo el mundo'),
(2, 'LEOPARDO', 'Felino manchado excelente para trepar a los árboles'),
(2, 'PANTERA', 'Felino de pelaje negro sigiloso y gran cazador'),
(2, 'CANGURO', 'Mamífero marsupial australiano que se desplaza dando saltos'),
(2, 'KOALA', 'Marsupial australiano que se alimenta de hojas de eucalipto'),
(2, 'PINGUINO', 'Ave marina que no vuela pero nada de forma ágil'),
(2, 'FLAMENCO', 'Ave esbelta de plumaje rosado que vive en humedales'),
(2, 'TUCAN', 'Ave tropical con un pico grande y de colores llamativos'),
(2, 'PAVO', 'Ave de gran tamaño que despliega sus vistosas plumas'),
(2, 'COLIBRI', 'Ave muy pequeña que aletea extremadamente rápido'),
(2, 'CIGUEÑA', 'Ave de patas largas asociada a traer a los bebés'),
(2, 'LLAMA', 'Mamífero rumiante típico de los Andes sudamericanos'),
(2, 'ALPACA', 'Mamífero andino muy valorado por su lana suave'),
(2, 'CASTOR', 'Roedor hábil que construye presas de madera en ríos'),
(2, 'ARDILLA', 'Roedor trepador que guarda nueces para el invierno'),
(2, 'MAPACHE', 'Mamífero con antifaz negro en la cara muy curioso'),
(2, 'TEJON', 'Mamífero excavador de garras fuertes y hábitos nocturnos'),
(2, 'ZORRILLO', 'Pequeño mamífero famoso por defenderse con mal olor'),
(2, 'PANDA', 'Mamífero blanco y negro que se alimenta de bambú'),
(2, 'AVESTRUZ', 'Ave de gran tamaño y rápida veloz que no vuela'),
(2, 'PELICANO', 'Ave marina con una gran bolsa en su pico'),
(2, 'CAMALEON', 'Reptil que cambia de color para camuflarse en ramas'),
(2, 'SALAMANDRA', 'Anfibio de cuerpo alargado y piel húmeda y lisa'),
(2, 'ORNITORRINCO', 'Mamífero semiaquático australiano con pico de pato'),
(2, 'PIRAÑA', 'Pez de agua dulce de dientes muy afilados'),
(2, 'MANTARRAYA', 'Pez plano de gran tamaño que nada suavemente'),
(2, 'FOCA', 'Mamífero marino adaptado al frío con aletas suaves'),
(2, 'MARIPOSA', 'Insecto con alas vistosas de hermosos colores variados');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(3, 'SANTOS', 'Apellido tradicional vinculado a conceptos religiosos muy difundido'),
(3, 'ACOSTA', 'Apellido común de origen hispano muy frecuente en la región'),
(3, 'LARA', 'Apellido corto y noble de gran tradición en México'),
(3, 'OCHOA', 'Apellido de origen vasco muy popular en el país'),
(3, 'MEJIA', 'Apellido tradicional muy extendido en toda América Latina'),
(3, 'FIGUEROA', 'Apellido largo distintivo con gran presencia en registros civiles'),
(3, 'CABRERA', 'Apellido relacionado tradicionalmente con el cuidado del ganado'),
(3, 'VALENZUELA', 'Apellido largo y elegante muy común en el norte'),
(3, 'ROBLES', 'Apellido inspirado en el árbol fuerte de la naturaleza'),
(3, 'AGUIRRE', 'Apellido de origen vasco de arraigada tradición en México'),
(3, 'SANDOVAL', 'Apellido clásico y distinguido bastante común en el país'),
(3, 'RANGEL', 'Apellido tradicional muy arraigado en la sociedad mexicana'),
(3, 'PACHECO', 'Apellido de larga tradición familiar muy común en México'),
(3, 'MONTIEL', 'Apellido de origen geográfico bastante popular en familias'),
(3, 'DURAN', 'Apellido breve y tradicional de amplia difusión hispana'),
(3, 'MORA', 'Apellido corto que evoca el fruto silvestre de la zarza'),
(3, 'ESPINOSA', 'Variante muy popular del apellido relacionado con plantas'),
(3, 'VEGA', 'Apellido de origen geográfico que evoca terrenos fértiles'),
(3, 'SOSA', 'Apellido corto y muy popular en diversas regiones latinas'),
(3, 'LUNA', 'Apellido poético que hace referencia al satélite terrestre'),
(3, 'SERRANO', 'Apellido que hace referencia a los habitantes de la sierra'),
(3, 'CORONA', 'Apellido distinguido que evoca un símbolo de la realeza'),
(3, 'MARQUEZ', 'Apellido muy popular derivado de un título nobiliario histórico'),
(3, 'TAPIA', 'Apellido tradicional que evoca muros o protecciones de tierra'),
(3, 'TELLEZ', 'Apellido de origen patronímico muy común en varias familias'),
(3, 'MACIAS', 'Apellido bastante popular y reconocido en el territorio nacional'),
(3, 'GALLEGOS', 'Apellido de origen geográfico relativo a personas de Galicia'),
(3, 'ARELLANO', 'Apellido tradicional y muy conocido en la región mexicana'),
(3, 'CISNEROS', 'Apellido elegante de origen histórico bastante frecuente'),
(3, 'GALVAN', 'Apellido tradicional de origen antiguo de amplia difusión');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(5, 'PADEL', 'Deporte popular de raqueta jugado en pareja dentro de pista cerrada'),
(5, 'FRONTON', 'Deporte de pelota rebotada fuertemente contra una pared alta'),
(5, 'SQUASH', 'Deporte de raqueta jugado dentro de una cancha de cuatro paredes'),
(5, 'BADMINTON', 'Deporte de raqueta ligera donde se golpea un volante de plumas'),
(5, 'BILLAR', 'Deporte de precisión que se juega impulsando bolas con un taco'),
(5, 'BOLICHE', 'Deporte de precisión donde se derriban diez pinos con bola pesada'),
(5, 'RALLY', 'Competición de automovilismo por etapas en caminos y carreteras variadas'),
(5, 'KARTING', 'Disciplina de automovilismo de velocidad en pequeños vehículos sin carrocería'),
(5, 'MARATON', 'Carrera pedestre de gran resistencia sobre una distancia de cuarenta kilómetros'),
(5, 'CURLING', 'Deporte olímpico sobre hielo donde se deslizan piedras de granito pulido'),
(5, 'SURF', 'Deporte acuático que consiste en deslizarse de pie sobre una ola'),
(5, 'KICKBOXING', 'Deporte de contacto que combina golpes de boxeo con patadas fuertes'),
(5, 'WAKEBOARD', 'Deporte acuático donde el deportista se desliza arrastrado por lancha'),
(5, 'PARAPENTE', 'Deporte aéreo de vuelo libre utilizando un ala de tela flexible'),
(5, 'WATERPOLO', 'Deporte acuático en equipo jugado en piscina con arcos y balón');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(6, 'ESTAÑO', 'Metal blando que compone el bronce y las soldaduras'),
(6, 'BISMUTO', 'Metal pesado poco tóxico famoso por sus cristales iridiscentes'),
(6, 'ESTRONCIO', 'Metal alcalinotérreo que da color rojo a los fuegos artificiales'),
(6, 'CIRCONIO', 'Metal resistente a la corrosión usado en reactores y joyería'),
(6, 'RUBIDIO', 'Metal alcalino muy reactivo de bajo punto de fusión'),
(6, 'ANTIMONIO', 'Semimetal utilizado para endurecer aleaciones de plomo'),
(6, 'TELURIO', 'Metaloide poco común usado en paneles solares y cerámicas'),
(6, 'PLATINO', 'Metal noble y denso de altísimo valor comercial e industrial'),
(6, 'IRIDIO', 'Metal denso abundante en el asteroide que extinguió dinosaurios'),
(6, 'OSMIO', 'El elemento natural de mayor densidad de la tabla periódica'),
(6, 'PALADIO', 'Metal noble muy cotizado para convertidores catalíticos de autos'),
(6, 'RODIO', 'Metal de transición extremadamente raro y altamente reflector'),
(6, 'RUTENIO', 'Metal duro del grupo del platino usado en contactos eléctricos'),
(6, 'RENIO', 'Metal raro con uno de los puntos de fusión más altos'),
(6, 'INDIO', 'Metal blando esencial para pantallas táctiles y cristal líquido'),
(6, 'TALIO', 'Metal pesado sumamente tóxico usado históricamente en venenos'),
(6, 'CERIO', 'Lantánido más abundante utilizado en la piedra de encendedores'),
(6, 'LANTANO', 'Elemento que encabeza la serie de los lantánidos en la tabla'),
(6, 'NEODIMIO', 'Metal raro usado para fabricar los imanes permanentes más potentes'),
(6, 'PROMECIO', 'Único elemento lantánido que no posee isótopos estables'),
(6, 'SAMARIO', 'Elemento usado en imanes industriales de alta temperatura'),
(6, 'EUROPIO', 'Lantánido que fosforece en rojo en las pantallas de televisión'),
(6, 'GADOLINIO', 'Metal utilizado como agente de contraste en resonancias magnéticas'),
(6, 'TERBIO', 'Lantánido verde empleado en la fabricación de tubos fluorescentes'),
(6, 'DISPROSIO', 'Metal con alta capacidad de absorción de neutrones nucleares'),
(6, 'HOLMIO', 'Elemento con las mayores propiedades magnéticas de la naturaleza'),
(6, 'ERBIO', 'Lantánido rosado usado en amplificadores de fibra óptica'),
(6, 'TULIO', 'Uno de los elementos lantánidos más raros y costosos'),
(6, 'ITERBIO', 'Metal blando y maleable utilizado en relojes atómicos'),
(6, 'LUTECIO', 'El elemento más denso y duro de los lantánidos'),
(6, 'TORIO', 'Elemento radiactivo considerado alternativa limpia al uranio'),
(6, 'ACTINIO', 'Elemento que da nombre a la serie de los actínidos'),
(6, 'PROTACTINIO', 'Elemento radiactivo raro y extremadamente tóxico'),
(6, 'AMERICIO', 'Elemento sintético radiactivo presente en detectores de humo'),
(6, 'CALIFORNIO', 'Actínido sintético utilizado para iniciar reactores nucleares');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(9, 'BATIDORA', 'Electrodoméstico que mezcla o bate ingredientes rápidamente'),
(9, 'TOSTADORA', 'Aparato que dora rebanadas de pan con calor eléctrico'),
(9, 'LAVADORA', 'Electrodoméstico que limpia ropa automáticamente con agua y detergente'),
(9, 'SECADORA', 'Aparato que elimina la humedad de las prendas tras el lavado'),
(9, 'LAVAVAJILLAS', 'Electrodoméstico que limpia platos y cubiertos automáticamente'),
(9, 'TAPER', 'Recipiente de plástico con tapa para guardar comida sobrante'),
(9, 'RALLADOR', 'Utensilio con orificios afilados para desmenuzar alimentos duros'),
(9, 'EXPRIMIDOR', 'Aparato para extraer el jugo de frutas cítricas fácilmente'),
(9, 'ABRIDOR', 'Herramienta metálica para retirar corchos o tapas de botellas'),
(9, 'ABRELATAS', 'Utensilio diseñado para cortar la tapa de las latas'),
(9, 'PELADOR', 'Cuchillo especial para quitar la piel a frutas y verduras'),
(9, 'TABLA', 'Superficie de madera o plástico para cortar alimentos de forma segura'),
(9, 'RODILLO', 'Cilindro de madera para estirar masas de cocina uniformemente'),
(9, 'EMBUDO', 'Instrumento cónico para canalizar líquidos en recipientes de boca estrecha'),
(9, 'SOPERA', 'Recipiente grande con tapa para servir caldos en la mesa'),
(9, 'TAZA', 'Recipiente con asa para tomar bebidas calientes como café'),
(9, 'JARRA', 'Recipiente con asa y pico para servir líquidos en vasos'),
(9, 'COPA', 'Recipiente de cristal con pie elegante para servir vino'),
(9, 'ALACENA', 'Mueble de cocina con estantes para guardar alimentos y utensilios'),
(9, 'ESTANTE', 'Tabla horizontal fija a la pared para colocar libros u objetos'),
(9, 'LIBRERO', 'Mueble con repisas diseñado para organizar colecciones de libros'),
(9, 'BURO', 'Mesa pequeña situada al lado de la cama en el dormitorio'),
(9, 'ROPERO', 'Mueble alto y amplio diseñado para colgar y guardar ropa'),
(9, 'MECEDORA', 'Silla con patas curvas que permite balancearse suavemente adelante y atrás'),
(9, 'TABURETE', 'Asiento individual sin respaldo ni brazos para cocina o barra'),
(9, 'PUFF', 'Asiento blando de cojín sin patas ni respaldo para descansar'),
(9, 'COJIN', 'Almohadón pequeño decorativo para colocar en sofás o sillas'),
(9, 'CUBRECAMA', 'Manta ligera que se coloca sobre la cama para decorar'),
(9, 'SABANA', 'Lienzo de tela fina que cubre el colchón para dormir'),
(9, 'EDREDON', 'Cubierta gruesa y acolchada que abriga la cama en invierno'),
(9, 'TOALLA', 'Paño de felpa absorbente usado para secarse tras el baño'),
(9, 'CEPILLO', 'Utensilio de cerdas usado para peinar el cabello o limpiar'),
(9, 'CUBETA', 'Recipiente cilíndrico con asa para transportar agua al limpiar'),
(9, 'MACETA', 'Recipiente de barro o plástico donde se cultivan plantas domésticas'),
(9, 'FLORERO', 'Recipiente ornamental para colocar flores frescas con agua en mesas'),
(9, 'CUADRO', 'Lienzo o lámina enmarcada que se cuelga para decorar paredes'),
(9, 'TAPETE', 'Alfombra pequeña que se coloca en el suelo junto a puertas'),
(9, 'ALFOMBRA', 'Tejido grueso que cubre el suelo para dar calidez al hogar'),
(9, 'CANDELABRO', 'Soporte elegante con varias ramas para sostener velas encendidas'),
(9, 'PERCHA', 'Gancho de plástico o madera para colgar prendas en armarios');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(11, 'CHEVROLET', 'Marca automotriz estadounidense muy vendida en México'),
(11, 'VOLKSWAGEN', 'Marca automotriz alemana creadora de autos icónicos'),
(11, 'HONDA', 'Empresa japonesa famosa por sus autos y motocicletas'),
(11, 'MAZDA', 'Marca automotriz japonesa de diseño elegante'),
(11, 'HYUNDAI', 'Fabricante automotriz surcoreano muy popular'),
(11, 'KIA', 'Marca automotriz surcoreana de gran presencia nacional'),
(11, 'BMW', 'Marca alemana de vehículos de lujo y deportivos'),
(11, 'AUDI', 'Fabricante alemán de autos de alta gama e innovación'),
(11, 'MERCEDES', 'Marca alemana referente de elegancia y prestigio automotriz'),
(11, 'MARS', 'Gran empresa fabricante de chocolates y golosinas globales'),
(11, 'SNICKERS', 'Barra de chocolate rellena de turrón, cacahuate y caramelo'),
(11, 'MILKYWAY', 'Barra de chocolate suave rellena de caramelo fluido'),
(11, 'MMS', 'Pequeños chocolates confitados de colores de la marca Mars'),
(11, 'HERSHEY', 'Famosa marca estadounidense de chocolates y jarabe dulce'),
(11, 'FERRERO', 'Empresa italiana famosa por sus chocolates finos con avellana'),
(11, 'NUTELLA', 'Crema dulce de avellana con cacao para untar'),
(11, 'MARUCHAN', 'Sopa instantánea en vaso extremadamente popular en México'),
(11, 'KNORR', 'Marca de caldos, sazonadores y sopas para la cocina'),
(11, 'LACOSTEÑA', 'Empresa mexicana líder en chiles y alimentos enlatados'),
(11, 'HERDEZ', 'Marca tradicional mexicana de salsas, verduras y conservas'),
(11, 'MCCORMICK', 'Empresa conocida por sus mayonesas, mermeladas y especias'),
(11, 'MAIZENA', 'Marca famosa de fécula de maíz para atoles y postres'),
(11, 'LIPTON', 'Marca global de té helado y bebidas aromáticas'),
(11, 'SPRITE', 'Refresco gaseoso transparente de sabor lima y limón'),
(11, 'FANTA', 'Bebida refrescante con gas de sabor frutal muy conocida'),
(11, 'FRESCA', 'Refresco de toronja producido por la compañía Coca-Cola'),
(11, 'SIDRAL', 'Famoso refresco de manzana tradicional en México'),
(11, 'JUMEX', 'Empresa mexicana elaboradora de jugos y néctares de fruta'),
(11, 'DELVALLE', 'Marca de jugos y bebidas frutales muy distribuida'),
(11, 'GATORADE', 'Bebida deportiva rehidratante muy consumida por atletas'),
(11, 'REDBULL', 'Famosa marca global de bebidas energizantes en lata'),
(11, 'MONSTER', 'Conocida marca de bebidas energizantes de lata grande'),
(11, 'NESQUIK', 'Polvo sabor chocolate para mezclar con leche fría'),
(11, 'CHOCOMILK', 'Polvo fortificado de chocolate para leche tradicional en México'),
(11, 'ZUKO', 'Polvo para preparar agua de sabor frutal muy económico'),
(11, 'TANG', 'Polvo instantáneo refrescante para preparar bebidas de fruta'),
(11, 'CLOROX', 'Marca líder en productos blanqueadores y desinfectantes'),
(11, 'PINOL', 'Limpiador multiusos con aroma a pino muy usado en hogares'),
(11, 'FABULOSO', 'Limpiador líquido aromatizante para pisos muy popular'),
(11, 'SUAVITEL', 'Acondicionador de telas y suavizante para el lavado de ropa');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(12, 'UCRANIA', 'País de Europa oriental famoso por sus extensos campos de trigo'),
(12, 'CROACIA', 'País europeo famoso por su impresionante costa en el mar Adriático'),
(12, 'RUMANIA', 'País europeo conocido por la legendaria región de Transilvania'),
(12, 'HUNGRIA', 'País europeo famoso por su capital Budapest y el río Danubio'),
(12, 'SERBIA', 'País balcánico de Europa oriental con gran historia cultural'),
(12, 'ALBANIA', 'País del sudeste europeo con hermosas playas en los Balcanes'),
(12, 'BULGARIA', 'País europeo famoso por sus valles de rosas y su historia'),
(12, 'ESLOVAQUIA', 'País de Europa central famoso por sus castillos y montañas'),
(12, 'ESLOVENIA', 'País alpino conocido por sus pintorescos lagos y bosques verdes'),
(12, 'ISLANDIA', 'Isla nórdica famosa por sus volcanes, géiseres y fuentes termales'),
(12, 'FILIPINAS', 'Archipiélago asiático con miles de islas tropicales paradisíacas'),
(12, 'TAILANDIA', 'País asiático famoso por sus templos budistas y sus playas'),
(12, 'VIETNAM', 'País del sudeste asiático con rica gastronomía e historia'),
(12, 'CAMBOYA', 'País asiático famoso por el majestuoso complejo de templos Angkor'),
(12, 'NEPAL', 'País montañoso albergue del famoso monte Everest en los Himalayas'),
(12, 'MONGOLIA', 'País de extensas estepas conocido por la cultura de nómadas'),
(12, 'LETONIA', 'País báltico europeo con hermosos bosques y playas de arena'),
(12, 'LITUANIA', 'País báltico europeo rico en historia y arquitectura antigua'),
(12, 'ESTONIA', 'País báltico de Europa avanzado en tecnología y servicios digitales'),
(12, 'MALTA', 'Isla europea del Mediterráneo con fortalezas históricas y aguas cristalinas'),
(12, 'CHIPRE', 'Isla del mar Mediterráneo rica en mitología y playas soleadas'),
(12, 'LIBANO', 'País del Oriente Medio conocido por sus antiguos bosques de cedros'),
(12, 'JORDANIA', 'País del Oriente Medio donde se encuentra la antigua ciudad Petra'),
(12, 'QATAR', 'Pequeño y próspero país del golfo Pérsico rodeado de desierto'),
(12, 'EMIRATOS', 'País del golfo Pérsico famoso por sus rascacielos y lujo'),
(12, 'KAZAJISTAN', 'Extenso país de Asia central con vasta estepa y recursos'),
(12, 'AFGANISTAN', 'País montañoso de Asia central con rica cultura e historia'),
(12, 'BANGLADESH', 'País asiático muy poblado rodeado casi por completo por India'),
(12, 'SENEGAL', 'País de África occidental famoso por su música e historia'),
(12, 'NIGERIA', 'El país más poblado de África con gran industria de cine'),
(12, 'KENIA', 'País africano famoso por sus safaris y la gran reserva Masai'),
(12, 'TANZANIA', 'País africano donde se encuentra el monte Kilimanjaro y Zanzíbar'),
(12, 'GHANA', 'País de África occidental conocido por su historia y producción cacao'),
(12, 'CAMERUN', 'País africano con gran diversidad geográfica y pasión futbolística'),
(12, 'ETIOPIA', 'País africano con historia milenaria y origen de la planta café'),
(12, 'MADAGASCAR', 'Gran isla africana famosa por su fauna única como los lémures'),
(12, 'ARGELIA', 'País más grande de África con gran territorio en el desierto'),
(12, 'TUNEZ', 'País del norte de África con ruinas antiguas de la ciudad Cartago'),
(12, 'ZIMBABUE', 'País africano famoso por albergar las impresionantes cataratas Victoria'),
(12, 'MOZAMBIQUE', 'País africano de extensa costa frente al océano Índico tropical');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(14, 'CHALECO', 'Prenda sin mangas que se usa sobre la camisa'),
(14, 'MOCASIN', 'Calzado de cuero cómodo y sin cordones'),
(14, 'TACONES', 'Calzado femenino elegante con elevación en el talón'),
(14, 'ZAPATILLA', 'Calzado ligero o de baile de suela delgada'),
(14, 'CHANCLAS', 'Calzado muy ligero y abierto para uso en playa'),
(14, 'BOINA', 'Gorra plana de lana sin visera de estilo tradicional'),
(14, 'CORBATIN', 'Accesorio formal en forma de moño para el cuello'),
(14, 'TUXEDO', 'Traje de etiqueta muy elegante usado en galas'),
(14, 'GAFAS', 'Accesorio con cristales para proteger los ojos del sol'),
(14, 'ANILLO', 'Joya circular que se lleva como adorno en los dedos'),
(14, 'COLLAR', 'Adorno o joya que se lleva alrededor del cuello'),
(14, 'PULSERA', 'Adorno que se lleva rodeando la muñeca'),
(14, 'ARETES', 'Joyas o adornos que se colocan en las orejas'),
(14, 'MOCHILA', 'Bolsa que se lleva a la espalda para cargar objetos'),
(14, 'BOLSA', 'Accesorio usado para llevar objetos personales diarios'),
(14, 'CARTERA', 'Accesorio pequeño para guardar dinero y credenciales'),
(14, 'MALETA', 'Equipaje con asa usado para transportar ropa en viajes'),
(14, 'PARAGUAS', 'Objeto portátil desplegable para protegerse de la lluvia'),
(14, 'ABANICO', 'Accesorio manual desplegable usado para dar aire fresco'),
(14, 'GABARDINA', 'Abrigo largo e impermeable resistente al viento y lluvia');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(7, 'CEMPASUCHIL', 'Flor tradicional mexicana de color anaranjado usada en altares'),
(7, 'NOCHEBUENA', 'Planta de hojas rojas muy representativa de la época navideña'),
(7, 'GLADIOLA', 'Flor alta y elegante cultivada para arreglos de ornato'),
(7, 'ALCATRAZ', 'Flor blanca en forma de copa con tallo largo'),
(7, 'BEGONIA', 'Planta decorativa de sombras con flores vistosas de colores'),
(7, 'PENSAMIENTO', 'Flor pequeña de jardín con pétalos de variados tonos'),
(7, 'IRIS', 'Flor vistosa de colores morados e intensos de primavera'),
(7, 'ACACIA', 'Árbol frondoso con pequeñas flores amarillas muy aromáticas'),
(7, 'ABETO', 'Árbol conífero alto muy utilizado tradicionalmente como árbol navideño'),
(7, 'ALAMO', 'Árbol alto de hojas ligeras que crecen junto a ríos'),
(7, 'CIPRES', 'Árbol alto y delgado muy común en jardines y cementerios'),
(7, 'EUCALIPTO', 'Árbol aromático de hojas medicinales muy usado para infusiones'),
(7, 'FICUS', 'Planta o árbol ornamental de interiores y jardines urbanos'),
(7, 'MAGUEY', 'Planta de hojas carnosas usada para producir pulque y mezcal'),
(7, 'AGAVE', 'Planta mexicana emblemática usada para la elaboración del tequila'),
(7, 'SABILA', 'Planta suculenta de pencas carnosas con gel medicinal interior'),
(7, 'BONSAI', 'Árbol enano cultivado en macetas mediante técnicas especiales orientales'),
(7, 'MANZANILLA', 'Hierba aromática de pequeñas flores medicinal para tés relajantes'),
(7, 'MEZQUITE', 'Árbol espinoso muy resistente típico de zonas áridas mexicanas'),
(7, 'HUIZACHE', 'Arbusto o árbol espinoso muy común en el centro de México');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(1, 'CHURROS', 'Masa frita azucarada'),
(1, 'CAJETA', 'Dulce de leche de cabra tradicional muy espeso'),
(1, 'ATE', 'Dulce de frutas compacto típico de Michoacán'),
(1, 'CAMOTE', 'Tubérculo dulce preparado tradicionalmente con piloncillo'),
(1, 'PANCITA', 'Caldo picante de estómago de res muy popular'),
(1, 'MACHACA', 'Carne seca deshebrada norteña ideal con huevo'),
(1, 'CABRITO', 'Cría de cabra asada tradicional del norte mexicano'),
(1, 'CECINA', 'Carne de res o cerdo salada y secada al sol'),
(2, 'MANDRIL', 'Primate de cara colorida y gran tamaño'),
(2, 'LINCE', 'Felino de orejas puntiagudas y excelente visión'),
(2, 'PUMA', 'Felino grande de montaña de color pardo'),
(2, 'JABALI', 'Cerdo salvaje de largos colmillos curvos'),
(2, 'HIENA', 'Carnívoro africano famoso por su sonido parecido a risa'),
(2, 'ARMADILLO', 'Mamífero con caparazón de placas protectoras articuladas'),
(2, 'TAPIR', 'Mamífero herbívoro de trompa corta típico de selvas'),
(2, 'MANATI', 'Gran mamífero acuático herbívoro de movimientos lentos'),
(3, 'CARDENAS', 'Apellido patronímico de origen español muy respetado'),
(3, 'ESCALANTE', 'Apellido antiguo originario del norte de la península ibérica'),
(3, 'SALINAS', 'Apellido geográfico referente a la explotación de sal'),
(3, 'NAVARRETE', 'Apellido originario de la zona de Navarra'),
(3, 'QUINTERO', 'Apellido hispano relacionado con arrendatarios de tierras'),
(3, 'BLANCO', 'Apellido referente a las características físicas o pureza'),
(3, 'MEDRANO', 'Apellido distinguido bastante presente en estados del centro'),
(3, 'GUEVARA', 'Apellido famoso de origen vasco muy internacionalizado'),
(5, 'TAICHI', 'Arte marcial chino de movimientos muy suaves y lentos'),
(5, 'KUNGFU', 'Arte marcial chino de movimientos suaves'),
(5, 'AIKIDO', 'Arte marcial japonés enfocado en defensa y redirección'),
(5, 'SKELETON', 'Deporte olímpico de invierno deslizando boca abajo sobre trineo'),
(5, 'BOBSLEIGH', 'Deporte invernal de descenso en trineo de varias plazas'),
(5, 'WINDSURF', 'Deporte acuático que combina tabla con una pequeña vela'),
(5, 'KITESURF', 'Deporte acuático impulsado por un cometa de tracción'),
(5, 'CAPOEIRA', 'Arte marcial brasileño que combina danza acrobacias y música'),
(5, 'PARKOUR', 'Disciplina física enfocada en superar obstáculos urbanos rápidamente'),
(6, 'CURIUM', 'Elemento radiactivo sintético que rinde homenaje a los Curie'),
(6, 'MENDELEVIO', 'Actínido sintético nombrado en honor al creador de la tabla'),
(6, 'FERMIO', 'Elemento sintético altamente radiactivo del grupo actínido'),
(6, 'EINSTEINIO', 'Elemento radiactivo cuyo nombre rinde homenaje a un famoso físico'),
(6, 'NOBELIO', 'Elemento de vida muy corta que honra a Alfred Nobel'),
(6, 'LAURENCIO', 'Elemento radiactivo que rinde tributo al creador del ciclotrón'),
(6, 'FRANCIO', 'Metal alcalino extremadamente raro y altamente radiactivo'),
(6, 'ASTATO', 'Halógeno radiactivo que es el elemento natural más raro'),
(7, 'JACARANDA', 'Árbol urbano que florece con vistosas flores color lila'),
(7, 'TABACHIN', 'Árbol tropical con hermosas y llamativas flores rojo anaranjado'),
(7, 'CEDRON', 'Arbusto cuyas hojas desprenden un agradable olor a limón'),
(7, 'GARDENIA', 'Flor blanca muy perfumada usada en ramos de novia'),
(7, 'ALELI', 'Flor aromática silvestre y ornamental de climas templados'),
(7, 'CLAVELINA', 'Flor parecida al clavel pero de tamaño más pequeño'),
(7, 'CUNA', 'Se refiere a la flor cuna de Moisés de hojas blancas'),
(7, 'PALMERA', 'Árbol exótico alto y de grandes hojas tropicales'),
(9, 'MOLCAJETE', 'Mortero de piedra volcánica para moler salsas mexicanas'),
(9, 'METATE', 'Piedra plana prehispánica para moler granos de maíz'),
(9, 'COMAL', 'Disco de barro o metal para calentar tortillas'),
(9, 'PLUMERO', 'Utensilio de plumas utilizado para sacudir el polvo fino'),
(9, 'CENICERO', 'Recipiente para depositar las cenizas de los cigarros'),
(9, 'SALERO', 'Pequeño recipiente con orificios para esparcir sal en comidas'),
(9, 'AZUCARERO', 'Recipiente de mesa usado para contener y servir azúcar'),
(9, 'HIELERA', 'Recipiente o caja aislante para conservar hielo y bebidas'),
(11, 'TELCEL', 'Compañía líder de telecomunicaciones móviles en el país'),
(11, 'MOVISTAR', 'Empresa española de telefonía celular con gran presencia local'),
(11, 'ATT', 'Compañía telefónica internacional de gran tamaño en comunicaciones'),
(11, 'IZZI', 'Empresa mexicana proveedora de internet y televisión por cable'),
(11, 'TOTALPLAY', 'Proveedor de internet de fibra óptica y entretenimiento digital'),
(11, 'MEGACABLE', 'Empresa de televisión restringida y banda ancha muy popular'),
(11, 'CINEMEX', 'Cadena de salas de cine con gran presencia nacional'),
(11, 'CINEPOLIS', 'La cadena de exhibición cinematográfica más grande de México'),
(12, 'MALI', 'País de África occidental conocido por su antigua ciudad Tombuctú'),
(12, 'CHAD', 'País africano que recibe su nombre por un gran lago interior'),
(12, 'SUDAN', 'País norafricano por donde atraviesa el gran río Nilo'),
(12, 'ANGOLA', 'País africano bañado por el océano Atlántico y rico en petróleo'),
(12, 'NAMIBIA', 'País del suroeste africano famoso por su vasto desierto rojo'),
(12, 'ZAMBIA', 'País africano que comparte las famosas cataratas Victoria'),
(12, 'OMAN', 'Sultanato de la península arábiga con historia comercial milenaria'),
(12, 'YEMEN', 'País del sur de Arabia con antigua tradición arquitectónica');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(17, 'VENTO', 'Sedán de Volkswagen muy popular en México'),
(17, 'GOL', 'Hatchback compacto y rendidor de Volkswagen'),
(17, 'TIIDA', 'Sedán de Nissan muy espacioso y popular'),
(17, 'PLATINA', 'Sedán clásico resultado de la alianza Nissan y Renault'),
(17, 'FUSION', 'Sedán mediano elegante y tecnológico de Ford'),
(17, 'SUPRA', 'Auto deportivo japonés legendario de la marca Toyota'),
(17, 'ESCORT', 'Auto compacto clásico muy querido de Ford'),
(17, 'CHEYENNE', 'Camioneta pick up de Chevrolet muy famosa'),
(17, 'RANGER', 'Camioneta de trabajo clásica de la marca Ford'),
(17, 'TAHOE', 'Camioneta SUV grande y robusta de Chevrolet');

INSERT INTO palabras (id_categoria, palabra, pista) VALUES
(19, 'MATEHUALA', 'Ciudad importante del altiplano en San Luis Potosí'),
(19, 'ZAPOPAN', 'Ciudad importante de Jalisco muy cercana a Guadalajara'),
(19, 'CORDOBA', 'Ciudad histórica del estado de Veracruz famosa por su café'),
(19, 'XOCHIMILCO', 'Delegación o ciudad de México famosa por sus canales'),
(20, 'TIBIA', 'Hueso largo situado en la parte inferior de la pierna'),
(20, 'PERONE', 'Hueso largo y delgado paralelo a la tibia en la pierna'),
(20, 'RADIO', 'Hueso largo del antebrazo del mismo lado del pulgar'),
(19, 'ZAMORA', 'Ciudad colonial del estado de Michoacán');
COMMIT;
